config/routes.rb
MomRails::Application.routes.draw do
  resources :sites

  resources :nameservers

  get 'route_reload' => 'welcome#route_reload'

  match 'reports' => 'reports#index', :as => 'reports'
  get 'reports/index', :as => 'index_reports'
  match 'reports/graph/:source_id/:destination_id/:metric_id' => 'reports#graph', :via => [:get]
  post 'reports/graph', :as =>'graph_reports'
  post 'reports/dygraphs_bruto', :as =>'dygraphs_bruto_reports'
  post 'reports/highcharts_bruto', :as =>'highcharts_bruto_reports'
  post 'reports/eaq_graph', :as =>'eaq_graph_reports'
  post 'reports/eaq_compliance_graph', :as =>'eaq_compliance_graph_reports'
  post 'reports/eaq_table', :as =>'eaq_table_reports'
  post 'reports/detail_eaq_table', :as =>'detail_eaq_table_reports'
  post 'reports/eaq2_table', :as => 'eaq2_table_reports'
  post 'reports/detail_eaq2_table', :as=> 'detail_eaq2_table_reports'
  post 'reports/detail_speed_type_eaq2_table', :as => 'detail_speed_type_eaq2_table_reports'
  post 'reports/detail_probe_eaq2_table', :as => 'detail_probe_eaq2_table_reports'
  post 'kpi/show' => 'kpi#show', :as => 'show_kpi'
  match 'reports/csv_bruto/:filename' => 'reports#csv_bruto', :as => 'reports_csv_bruto', :via => [:get]
  match 'reports/csv_diario/:filename' => 'reports#csv_diario', :as => 'reports_csv_diario', :via => [:get]
  match 'reports/csv_mensal/:filename' => 'reports#csv_mensal', :as => 'reports_csv_mensal', :via => [:get]
  match 'reports/xls_bruto/:filename' => 'reports#xls_bruto', :as => 'reports_xls_bruto', :via => [:get]
  match 'reports/xls_diario/:filename' => 'reports#xls_diario', :as => 'reports_xls_diario', :via => [:get]
  match 'reports/xls_mensal/:filename' => 'reports#xls_mensal', :as => 'reports_xls_mensal', :via => [:get]
  post 'reports/send' => 'reports#send_report', :as => 'send_reports'
  match 'reports/performance/:filename' => 'reports#performance', :as => 'reports_performance_export', :via => [:get]
  post 'reports/performance', :as => 'performance_reports'
  post 'reports/smartrate', :as => 'smartrate_reports'
  post 'reports/pacman', :as => 'pacman_reports'
  post 'reports/pacman_details', :as => 'pacman_details_reports'
  post 'reports/pacman_activity', :as => 'pacman_activity_reports'
  post 'reports/pacman_service_activity', :as => 'pacman_service_activity_reports'
  post 'reports/pacman_service_activity_details', :as => 'pacman_service_activity_details_reports'
  resources :metrics
  resources :tests
  resources :schedules
  get 'schedules/win/schedule' => 'schedules#win', :as => 'windows_schedules'
  post 'schedules/private_schedule' => 'schedules#private_schedule', :as => 'private_schedules'
  post 'schedules/private_agt_index' => 'schedules#private_agt_index', :as => 'private_agt_indexes'
  resources :probes do
    member do
      get 'destinations'
      get 'sources'

    end
  end

  post 'probes/load_location',:as=> 'probes_load_location'
  post 'probes/filter_uf', :as => 'probes_filter_uf'
  post 'probes/filter_destination', :as => 'probes_filter_destination'
  post 'probes/find_cns_by_state', :as => 'probes_find_cns_by_state'

  match 'probes/:id/metrics/:source_id' => 'probes#metrics', :via => [:get]
  match 'probes/:id/thresholds/:source_id' => 'probes#thresholds', :via => [:get]

  resources :metrics
  resources :process
  resources :profiles
  resources :dns_profiles
  resources :url_profiles
  resources :raw_xml_profiles
  resources :http_profiles

  resources :connection_profiles do
    resources :plans
  end
  resources :thresholds
  resources :plans

  devise_for :users #, :controllers => { :registrations => "registrations" }
  resources :users do
    get :active
  end
  as :user do
    put :update_password, :controller => :users
  end

  get 'users/sign_in'

  get 'welcome/index'

  match 'welcome/probe_list/:type' => 'welcome#probe_list', :via => [:get], :as => 'welcome_probe_list'
  get 'welcome/probe_list'

  match 'welcome/status/:source/:destination' => 'welcome#status', :via => [:get]

  get 'welcome/stats'

  match 'collect/id' => 'results#index'
  match 'collect/id/:destination_id/:metric_name/:dsmax/:dsmin/:dsavg/:sdmax/:sdmin/:sdavg/:timestamp/:uuid' => 'results#create',
        :via => [:get],
        :as => 'results_create',
        :constraints => { :destination_id => /\d+/,
                          :metric_name => /[a-z_]+/,
                          :dsmax => /[-]*[0-9]+[.]*[0-9]+/,
                          :dsmin => /[-]*[0-9]+[.]*[0-9]+/,
                          :dsavg => /[-]*[0-9]+[.]*[0-9]+/,
                          :sdmax => /[-]*[0-9]+[.]*[0-9]+/,
                          :sdmin => /[-]*[0-9]+[.]*[0-9]+/,
                          :sdavg => /[-]*[0-9]+[.]*[0-9]+/,
                          :timestamp => /\d+/,
                          :uuid => /[0-9A-Fa-f]+-[0-9A-Fa-f]+-[0-9A-Fa-f]+-[0-9A-Fa-f]+-[0-9A-Fa-f]+/
        }

  match 'collect/id/:destination_id/kpis/:cell_id/:brand/:model/:conn_type/:conn_tech/:signal/:error_rate/:change_of_ips/:route/:mtu/:dns_latency/:lac/:timestamp/:uuid' => 'kpi#create',
        :via => [:get],
        :as => 'kpi_create',
        :constraints => { :destination_id => /\d+/,
                          :cell_id => /[0-9\-]+/,
                          :brand => /.+/,
                          :model => /.+/,
                          :conn_type => /[A-Za-z+\-]+/,
                          :conn_tech => /[A-Za-z+\-]+/,
                          :signal => /[>|<|%3C|%3E]*[0-9.\- ]+|Desconhecido|unknown/,
                          :error_rate => /[>|<|%3C|%3E]*[0-9.\- ]+|Desconhecido|unknown'/,
                          :change_of_ips => /[0-9\-]+/,
                          :route => /.+/,
                          :mtu => /[0-9\-]+|Desconhecido/,
                          :dns_latency => /[%3C]*[0-9.\- ><]+|Desconhecido/,
                          :lac => /[0-9\-]+/,
                          :timestamp => /\d+/,
                          :uuid => /[0-9A-Fa-f]+-[0-9A-Fa-f]+-[0-9A-Fa-f]+-[0-9A-Fa-f]+-[0-9A-Fa-f]+/
        }

  match 'schedules/unused_profiles_form/:source_id/:destination_id' => 'schedules#unused_profiles_form',
        :constraints => {
            :source_id => /\d+/,
            :destination_id => /\d+/,
        }

  root :to => 'welcome#login'

end

app/models/report.rb
# == Schema Information
#
# Table name: reports
#
#  id         :integer          not null, primary key
#  user       :string(255)
#  uuid       :string
#  timestamp  :datetime
#  agent_type :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Report < ActiveRecord::Base
  attr_accessible :agent_type, :timestamp, :user, :uuid
end

app/controllers/reports_controller.rb
# coding: utf-8
class ReportsController < ApplicationController
  #escopos
  has_scope :by_city
  has_scope :by_state, :type => :array_or_string
  has_scope :by_type, :type => :array_or_string
  has_scope :by_pop, :type => :array_or_string
  has_scope :by_bras, :type => :array_or_string
  has_scope :is_anatel
  has_scope :by_modem, :type => :array_or_string
  has_scope :by_tech, :type => :array_or_string
  has_scope :by_conn_type, :type => :array_or_string
  #variaveis globais
  attr_accessor :smartrate_dns_total, :smartrate_dns_results

  def index
    @report_types = [
        ['Gráfico de Indicadores Anatel/EAQ - Consolidação Diária', 'eaq_graph'],
        ['Gráfico de Indicadores Anatel/EAQ - Consolidação Mensal', 'eaq_compliance_graph'],
        ['Gráfico de Dados Brutos', 'graph'],
        ['Tabela de Indicadores Anatel/EAQ', 'eaq_table']
    ]
  end

  def graph
    source = Probe.find(params[:source][:id])
    destination = Probe.find(params[:destination][:id])
    metric = Metric.find(params[:metric][:id])
    schedule = Schedule.where(:destination_id => destination.id).where(:source_id => source.id).all.last

    from = DateTime.parse(params[:date][:start]+' '+params[:time][:start]+' '+DateTime.current.zone).in_time_zone
    to = DateTime.parse(params[:date][:end]+' '+params[:time][:end]+' '+DateTime.current.zone).in_time_zone

    raw_results = Results.
        where(:schedule_id => schedule.id).
        where(:metric_id => metric.id).
        where(:timestamp => from..to).order('timestamp ASC').all

    results = []

    if metric.plugin != 'rtt'
      raw_results.each do |raw_result|
        results << {
            :x => raw_result.timestamp,
            :dsavg => raw_result.dsavg,
            :sdavg => raw_result.sdavg,
            :dsmin => raw_result.dsmin,
            :dsmax => raw_result.dsmax,
            :sdmin => raw_result.sdmin,
            :sdmax => raw_result.sdmax,
            :extra => {:uuid => raw_result.uuid}
        }
      end
    else
      raw_results.each do |raw_result|
        results << {
            :x => raw_result.timestamp,
            :dsavg => raw_result.dsavg,
            :dsmin => raw_result.dsmin,
            :dsmax => raw_result.dsmax,
            :extra => {:uuid => raw_result.uuid}
        }
      end
    end

    data = {
        :source => source,
        :destination => destination,
        :metric => metric,
        :schedule => schedule,
        :range => {:start => from, :end => to},
        :results => results
    }

    respond_to do |format|
      format.json { render :json => data, :status => 200 }
    end
  end

  def eaq2_table
    @uid = SecureRandom.uuid #id necessario para div
    @from = DateTime.parse(params[:date][:start])
    @to = DateTime.parse(params[:date][:end])
    @months = @from.all_months_until @to
    @months[0] = Date.parse(@from.to_s)
    @type = params[:agent] # android or linux
    @agent_type = params[:agent_type] # fixed or mobile, if linux
    @states = params[:state]
    @cn = params[:cn]
    @goal_filter = params[:goal_filter] #all,above or under
    @pop = params[:pop]
    @bras = params[:bras]


    if @type.include? "all"
      @type = ["android", "linux"]
      @agent_type = ["fixed", "mobile"]
    end


    if @agent_type.nil?
      @agent_type = ["fixed", "mobile"]
    end

    if @goal_filter.nil?
      @goal_filter = false
    end

    if @bras.nil?
      @bras = 'all'
    end

    # Garantir que não tenhamos nulos
    @cn.delete("")
    @states.delete("")

    if @agent_type.include? 'fixed'
      fixed_conn_profile = ConnectionProfile.
          where(:conn_type => "fixed")
    else
      fixed_conn_profile = nil
    end

    if @agent_type.include? 'mobile'
      mobile_conn_profile = ConnectionProfile.
          where(:conn_type => "mobile")
    else
      mobile_conn_profile = nil
    end

    if !(@pop.include? 'all') && !(@bras.include? 'all')
      fixed_probes = Probe.
          where(:connection_profile_id => fixed_conn_profile).
          where(:state => @states).
          where(:areacode => @cn).
          where(:type => @type).
          where(:anatel => @goal_filter).
          where(:pop => @pop).
          where(:bras => @bras)

      mobile_probes = Probe.
          where(:connection_profile_id => mobile_conn_profile).
          where(:state => @states).
          where(:areacode => @cn).
          where(:type => @type).
          where(:anatel => @goal_filter).
          where(:pop => @pop).
          where(:bras => @bras)

    else
      if (@pop.include? 'all') && (@bras.include? 'all')
        fixed_probes = Probe.
            where(:connection_profile_id => fixed_conn_profile).
            where(:state => @states).
            where(:areacode => @cn).
            where(:type => @type).
            where(:anatel => @goal_filter)

        mobile_probes = Probe.
            where(:connection_profile_id => mobile_conn_profile).
            where(:state => @states).
            where(:areacode => @cn).
            where(:type => @type).
            where(:anatel => @goal_filter)

        all_probes = Probe.
            where(:state => @states).
            where(:areacode => @cn).
            where(:type => @type).
            where(:anatel => @goal_filter).
            by_conn_type(@agent_type)
      else
        if @pop.include? 'all'
          fixed_probes = Probe.
              where(:connection_profile_id => fixed_conn_profile).
              where(:state => @states).
              where(:areacode => @cn).
              where(:type => @type).
              where(:anatel => @goal_filter).
              where(:bras => @bras)

          mobile_probes = Probe.
              where(:connection_profile_id => mobile_conn_profile).
              where(:state => @states).
              where(:areacode => @cn).
              where(:type => @type).
              where(:anatel => @goal_filter).
              where(:bras => @bras)

          all_probes = Probe.
              where(:state => @states).
              where(:areacode => @cn).
              where(:type => @type).
              where(:anatel => @goal_filter).
              where(:bras => @bras).
              by_conn_type(@agent_type)

        else
          if @bras.include? 'all'
            fixed_probes = Probe.
                where(:connection_profile_id => fixed_conn_profile).
                where(:state => @states).
                where(:areacode => @cn).
                where(:type => @type).
                where(:anatel => @goal_filter).
                where(:pop => @pop)

            mobile_probes = Probe.
                where(:connection_profile_id => mobile_conn_profile).
                where(:state => @states).
                where(:areacode => @cn).
                where(:type => @type).
                where(:anatel => @goal_filter).
                where(:pop => @pop)

            all_probes = Probe.
                where(:state => @states).
                where(:areacode => @cn).
                where(:type => @type).
                where(:anatel => @goal_filter).
                where(:pop => @pop).
                by_conn_type(@agent_type)
          end
        end
      end
    end


    fixed_schedules = Schedule.
        where(:destination_id => fixed_probes)

    mobile_schedules = Schedule.
        where(:destination_id => mobile_probes)

    all_schedules = Schedule.
        where(:destination_id => all_probes)


    @report_results = {}
    #
    #  SCM4
    #
    @report_results[:scm4] = {}
    @medians_scm4 = Median.
        where('start_timestamp >= ?', @from).
        where('end_timestamp <= ?', @to).
        where(:schedule_id => fixed_schedules).
        where(:threshold_id => 1).
        order('start_timestamp ASC').all
    #
    # SMP10
    #
    @report_results[:smp10] = {}
    @medians_smp10 = Median.
        where('start_timestamp >= ?', @from).
        where('end_timestamp <= ?', @to).
        where(:schedule_id => mobile_schedules).
        where(:threshold_id => 1).
        order('start_timestamp ASC').all
    #
    # SCM5
    #
    @report_results[:scm5] = {}
    @medians_scm5 = Median.
        where('start_timestamp >= ?', @from).
        where('end_timestamp <= ?', @to).
        where(:schedule_id => fixed_schedules).
        where(:threshold_id => 2).
        order('start_timestamp ASC').all

    #
    # SMP11
    #
    @report_results[:smp11] = {}
    @medians_smp11 = Median.
        where('start_timestamp >= ?', @from).
        where('end_timestamp <= ?', @to).
        where(:schedule_id => mobile_schedules).
        where(:threshold_id => 2).
        order('start_timestamp ASC').all

    #
    # SCM6
    #
    @report_results[:scm6] = {}
    @medians_scm6 = Median.
        where('start_timestamp >= ?', @from).
        where('end_timestamp <= ?', @to).
        where(:schedule_id => all_schedules).
        where(:threshold_id => 3).
        order('start_timestamp ASC').all

    #
    # SCM7
    #
    @report_results[:scm7] = {}
    @medians_scm7 = Median.
        where('start_timestamp >= ?', @from).
        where('end_timestamp <= ?', @to).
        where(:schedule_id => all_schedules).
        where(:threshold_id => 4).
        order('start_timestamp ASC').all

    #
    # SCM8
    #
    @report_results[:scm8] = {}
    @medians_scm8 = Median.
        where('start_timestamp >= ?', @from).
        where('end_timestamp <= ?', @to).
        where(:schedule_id => all_schedules).
        where(:threshold_id => 5).
        order('start_timestamp ASC').all

    #
    # SCM9
    #
    @report_results[:scm9] = {}
    @medians_scm9 = Median.
        where('start_timestamp >= ?', @from).
        where('end_timestamp <= ?', @to).
        where(:schedule_id => all_schedules).
        where(:threshold_id => 6).
        order('start_timestamp ASC').all

    #
    # Calculo de todas as medias de thresholds
    #
    @months.each do |month|
      # SCM4
      count4 = 0
      count_all4 = 0

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/performance/dygraphs_active.html.erb
<div id="box-<%= @idName %>" class="row-fluid">
  <div class="span12">
    <div class="row-fluid">
      <div class="span12">
        <h5 style="text-align: center"><%= @metric.name %> | Origem: <%= @source.name %> |
          Destino: <%= @destination.name %> |
          Data: <%= @from.strftime('%Y-%m-%d %H:%M:%S %Z') %> à <%= @to.strftime('%Y-%m-%d %H:%M:%S %Z') %></h5>

        <div id="chart-<%= @idName %>" style="height:250px;"></div>
      </div>
    </div>
    <div class="row-fluid">
      <div class="span12">
        <div class="chart-bottom" style="padding-top: 10px;">
          <div class="btn btn-danger" style="float:right; margin-bottom: 20px" onclick="jQuery('#box-<%=@idName%>').remove(); delete graphs['<%=@idName%>']; delete params['<%=@idName%>']; delete graphData['<%=@idName%>'];">Remover</div>
          <a id="export-<%= @idName %>" class="btn btn-success" style="float:right; margin-right: 5px ;margin-bottom: 20px" href="<%= reports_performance_export_url @exportFileName+".csv" %>?<%= params.to_query %>">Exportar
            CSV</a>
          <a id="exportxls-<%= @idName %>" class="btn btn-success" style="float:right; margin-right: 5px ;margin-bottom: 20px" href="<%= reports_xls_bruto_url @exportFileName+".xls" %>?<%= @exportParams %>">Exportar
            XLS</a>
          <small>Próxima atualização deste gráfico <span class="update" id="update-<%= @idName %>">X</span></small>
          <div id="legend-<%= @idName %>" style="float:right; margin-right: 5px ;margin-bottom: 20px">Ponto Atual:</div>
        </div>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
    <% case @metric.plugin %>
    <% when 'rtt' %>
    graphData["<%=@idName%>"] = [
        <% @raw_results.each do |res| %>
        [new Date("<%= res.timestamp.strftime("%b %d, %Y %H:%M:%S %z")%>"), "<%=res.uuid%>", <%=res.pretty_scalar_upload%>]<%=(res!=@raw_results.last)?",":""%>
        <% end %>
    ];
    <% else %>
    graphData["<%=@idName%>"] = [
        <% @raw_results.each do |res| %>
        [new Date("<%= res.timestamp.strftime("%b %d, %Y %H:%M:%S %z")%>"), "<%=res.uuid%>", <%= res.pretty_scalar_download %>, <%= res.pretty_scalar_upload %>]<%=(res!=@raw_results.last)?",":""%>
        <% end %>
    ];
    <% end %>

    graphs["<%=@idName%>"] = new Dygraph(
            document.getElementById("chart-<%=@idName%>"),
            graphData["<%=@idName%>"],
            {
                labels: <%= @labels.clone.unshift('Data','uuid').to_json.html_safe %>,
                visibility: <%= ([true]*@labels.count).unshift(false).to_json.html_safe %>,
                labelsDiv: document.getElementById('legend-<%=@idName%>'),
                legend: "always",
                axisLabelFontSize: 10,
                ylabel: "<%=@metric.name%> (<%=@metric.view_unit%>)",
                yLabelWidth: 14,
                dateWindow: [Date.parse("<%=@from.strftime("%b %d, %Y %H:%M:%S %z")%>"), Date.parse("<%=@to.strftime("%b %d, %Y %H:%M:%S %z")%>")],
                clickCallback: function (e, x, pts) {
                    jQuery.ajax({
                        url: "<%=show_kpi_url%>",
                        type: 'post',
                        dataType: 'json',
                        data: {
                            uuid: graphs["<%=@idName%>"].file_[pts[0].idx][1]
                        },
                        success: function (kpi) {
                            if (!jQuery.isEmptyObject(kpi)) {
                                var extras = '';
                                extras += '<b>Timestamp: </b>' + moment(kpi.timestamp).format('YYYY-MM-DD HH:mm:ss Z') + '<br />';
                                extras += '<b>LAC: </b>' + kpi.lac + '<br />' + '<b>CELLID: </b>' + kpi.cell_id + '<br />';
                                extras += '<b>Marca: </b>' + kpi.brand + '<br />' + '<b>Modelo: </b>' + kpi.model + '<br />';
                                extras += '<b>Tec. Conex.: </b>' + kpi.conn_tech + '<br />' + '<b>Sinal: </b>' + kpi.signal + 'dB<br />';
                                extras += '<b>Atraso DNS: </b>' + kpi.dns_latency + 'ms<br />';
                                jQuery.pnotify({
                                    title: "KPI Info",
                                    text: extras,
                                    type: 'success'
                                });
                            } else {
                                jQuery.pnotify({
                                    title: "KPI Info",
                                    text: "Este ponto não possui informação KPI disponíveis"
                                });
                            }

                        },
                        error: function (status, msg, error) {
                            jQuery.pnotify({
                                title: "KPI Info",
                                text: "Algum erro ocorreu na hora de consultar os KPIs: " + msg,
                                type: 'error'
                            });
                        },
                        headers: {
                            'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
                        }
                    });
                }
            }
    );
    params["<%=@idName%>"] = <%= params.to_json.html_safe %>;
    params["<%=@idName%>"].from = new Date(<%=@raw_results.last[0].to_i%>000);
    tempUpdtObj["<%=@idName%>"] = {
        endDate: moment().add('m', <%= @window_size %>),
        callBack: function (me) {
            if (params["<%=@idName%>"] != undefined) {
                jQuery(me).text("Atualizando os dados");
                jQuery.post('<%=performance_reports_url%>.json', params["<%=@idName%>"]).done(function (dataReturned) {
                    jQuery.each(dataReturned.results, function (i, val) {
                        val[0] = new Date(val[0]);
                    });
                    graphData["<%=@idName%>"].shift();
                    graphData["<%=@idName%>"] = graphData["<%=@idName%>"].concat(dataReturned.results);
                    jQuery("#graph-date-<%=@idName%>").text("Data: " + moment(graphData["<%=@idName%>"][0][0]).format('YYYY-MM-DD HH:mm:ss Z') + " à " + moment.unix(dataReturned.to).format('YYYY-MM-DD HH:mm:ss Z'));
                    graphs["<%=@idName%>"].updateOptions({'file': graphData["<%=@idName%>"], dateWindow: [graphData["<%=@idName%>"][0][0], moment.unix(dataReturned.to)]});
                    var tempUpdtObj2 = jQuery.extend({}, tempUpdtObj["<%=@idName%>"]);
                    tempUpdtObj2.endDate = moment().add('m', <%= @window_size %>);
                    jQuery("#update-<%=@idName%>").regressiveTimer(tempUpdtObj2);
                });
            }
        }
    }
    jQuery("#update-<%=@idName%>").regressiveTimer(jQuery.extend({}, tempUpdtObj["<%=@idName%>"]));

</script>

app/views/reports/performance/dygraphs_dns.html.erb
<div id="box-<%=@idName%>" class="row-fluid">
  <div class="span12">
    <div class="row-fluid">
      <div class="span12">
        <h5 style="text-align: center">Origem: <%= @source.name %> | Destino: <%= @destination.name %> |
          <span id="graph-date-<%=@idName%>">Data: <%= @from.strftime('%Y-%m-%d %H:%M:%S %Z') %> à <%= @to.strftime('%Y-%m-%d %H:%M:%S %Z') %></span></h5>
        <div id="chart-<%= @idName %>" style="height:250px;"></div>
      </div>
    </div>
    <div class="row-fluid">
      <div class="span12">
        <div class="chart-bottom" style="padding-top: 10px;">
          <div class="btn btn-danger" style="float:right; margin-bottom: 20px" onclick="jQuery('#box-<%=@idName%>').remove(); delete graphs['<%=@idName%>']; delete params['<%=@idName%>']; delete tempUpdtObj['<%=@idName%>'];">Remover</div>
          <a id="export-<%= @idName %>" class="btn btn-success" style="float:right; margin-right: 5px ;margin-bottom: 20px" href="<%= reports_performance_export_url @exportFileName+".csv" %>?<%= params.to_query %>">Exportar
            CSV</a>
          <a id="exportxls-<%= @idName %>" class="btn btn-success" style="float:right; margin-right: 5px ;margin-bottom: 20px" href="<%= reports_performance_export_url @exportFileName+".xls" %>?<%= params.to_query %>">Exportar
            XLS</a>
          <small>Próxima atualização deste gráfico <span class="update" id="update-<%= @idName %>">X</span></small>
          <div id="legend-<%= @idName %>" style="float:right; margin-right: 5px ;margin-bottom: 20px">Ponto Atual:</div>
        </div>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
    graphData["<%=@idName%>"] = [
                <% @results.each do |res| %>
                [new Date("<%= res[0].strftime("%b %d, %Y %H:%M:%S %z")%>"),<%=res.drop(1).map{|x| x.nil? ? "null":x }.join(', ').chomp(', ') %>]<%=(res!=@results.last)?",":""%>
                <% end %>
            ];
    graphs["<%=@idName%>"] = new Dygraph(
            document.getElementById("chart-<%=@idName%>"),
            graphData["<%=@idName%>"] ,
    {
        labels: ["Data", <%= @labels.map{|x|"\"#{x}\""}.join(', ').chomp(', ').html_safe %>],
        labelsDiv: document.getElementById('legend-<%=@idName%>'),
        legend: "always",
        axisLabelFontSize: 10,
        ylabel: "<%=@metric.name%> (<%=@metric.db_unit%>)",
        yLabelWidth: 14,
        dateWindow: [Date.parse("<%=@from.strftime("%b %d, %Y %H:%M:%S %z")%>"),Date.parse("<%=@to.strftime("%b %d, %Y %H:%M:%S %z")%>")]
    });

    params["<%=@idName%>"] = <%= params.to_json.html_safe %>;
    params["<%=@idName%>"].from = new Date(<%=@results.last[0].to_i unless @results.last.nil? %>000);
    tempUpdtObj["<%=@idName%>"] = {
      endDate: moment().add('m', <%= @window_size %>),
      callBack: function (me) {
        if(params["<%=@idName%>"] != undefined) {
          jQuery(me).text("Atualizando os dados");
          jQuery.post('<%=performance_reports_url%>.json', params["<%=@idName%>"]).done(function (dataReturned) {
            jQuery.each(dataReturned.results, function(i,val) {
              val[0] = new Date(val[0]);
            });
            graphData["<%=@idName%>"].shift();
            graphData["<%=@idName%>"]= graphData["<%=@idName%>"].concat(dataReturned.results);
            jQuery("#graph-date-<%=@idName%>").text("Data: "+moment(graphData["<%=@idName%>"][0][0]).format('YYYY-MM-DD HH:mm:ss Z')+" à "+moment.unix(dataReturned.to).format('YYYY-MM-DD HH:mm:ss Z'));
            graphs["<%=@idName%>"].updateOptions({'file':graphData["<%=@idName%>"],dateWindow: [graphData["<%=@idName%>"][0][0],moment.unix(dataReturned.to)]});
            var tempUpdtObj2 = jQuery.extend({},tempUpdtObj["<%=@idName%>"]);
            tempUpdtObj2.endDate = moment().add('m', <%= @window_size %>);
            jQuery("#update-<%=@idName%>").regressiveTimer(tempUpdtObj2);
          });
        }
      }
    } 
    jQuery("#update-<%=@idName%>").regressiveTimer(jQuery.extend({},tempUpdtObj["<%=@idName%>"]));
</script>

app/views/reports/performance/dygraphs_notsupported.html.erb
Tipo de gráfico não suportado