config/routes.rb
MomRails::Application.routes.draw do
  resources :sites

  resources :nameservers

  get 'route_reload' => 'welcome#route_reload'

  match 'reports' => 'reports#index', :as => 'reports'
  get 'reports/index', :as => 'index_reports'
  match 'reports/graph/:source_id/:destination_id/:metric_id' => 'reports#graph', :via => [:get]
  post 'reports/graph', :as =>'graph_reports'
  post 'reports/dygraphs_bruto', :as =>'dygraphs_bruto_reports'
  post 'reports/highcharts_bruto', :as =>'highcharts_bruto_reports'
  post 'reports/eaq_graph', :as =>'eaq_graph_reports'
  post 'reports/eaq_compliance_graph', :as =>'eaq_compliance_graph_reports'
  post 'reports/eaq_table', :as =>'eaq_table_reports'
  post 'reports/detail_eaq_table', :as =>'detail_eaq_table_reports'
  post 'reports/eaq2_table', :as => 'eaq2_table_reports'
  post 'reports/detail_eaq2_table', :as=> 'detail_eaq2_table_reports'
  post 'reports/detail_speed_type_eaq2_table', :as => 'detail_speed_type_eaq2_table_reports'
  post 'reports/detail_probe_eaq2_table', :as => 'detail_probe_eaq2_table_reports'
  post 'kpi/show' => 'kpi#show', :as => 'show_kpi'
  match 'reports/csv_bruto/:filename' => 'reports#csv_bruto', :as => 'reports_csv_bruto', :via => [:get]
  match 'reports/csv_diario/:filename' => 'reports#csv_diario', :as => 'reports_csv_diario', :via => [:get]
  match 'reports/csv_mensal/:filename' => 'reports#csv_mensal', :as => 'reports_csv_mensal', :via => [:get]
  match 'reports/xls_bruto/:filename' => 'reports#xls_bruto', :as => 'reports_xls_bruto', :via => [:get]
  match 'reports/xls_diario/:filename' => 'reports#xls_diario', :as => 'reports_xls_diario', :via => [:get]
  match 'reports/xls_mensal/:filename' => 'reports#xls_mensal', :as => 'reports_xls_mensal', :via => [:get]
  post 'reports/send' => 'reports#send_report', :as => 'send_reports'
  match 'reports/performance/:filename' => 'reports#performance', :as => 'reports_performance_export', :via => [:get]
  post 'reports/performance', :as => 'performance_reports'
  post 'reports/smartrate', :as => 'smartrate_reports'
  post 'reports/pacman', :as => 'pacman_reports'
  post 'reports/pacman_details', :as => 'pacman_details_reports'
  post 'reports/pacman_activity', :as => 'pacman_activity_reports'
  post 'reports/pacman_service_activity', :as => 'pacman_service_activity_reports'
  post 'reports/pacman_service_activity_details', :as => 'pacman_service_activity_details_reports'
  resources :metrics
  resources :tests
  resources :schedules
  get 'schedules/win/schedule' => 'schedules#win', :as => 'windows_schedules'
  post 'schedules/private_schedule' => 'schedules#private_schedule', :as => 'private_schedules'
  post 'schedules/private_agt_index' => 'schedules#private_agt_index', :as => 'private_agt_indexes'
  resources :probes do
    member do
      get 'destinations'
      get 'sources'

    end
  end

  post 'probes/load_location',:as=> 'probes_load_location'
  post 'probes/filter_uf', :as => 'probes_filter_uf'
  post 'probes/filter_destination', :as => 'probes_filter_destination'
  post 'probes/find_cns_by_state', :as => 'probes_find_cns_by_state'

  match 'probes/:id/metrics/:source_id' => 'probes#metrics', :via => [:get]
  match 'probes/:id/thresholds/:source_id' => 'probes#thresholds', :via => [:get]

  resources :metrics
  resources :process
  resources :profiles
  resources :dns_profiles
  resources :url_profiles
  resources :raw_xml_profiles
  resources :http_profiles

  resources :connection_profiles do
    resources :plans
  end
  resources :thresholds
  resources :plans

  devise_for :users #, :controllers => { :registrations => "registrations" }
  resources :users do
    get :active
  end
  as :user do
    put :update_password, :controller => :users
  end

  get 'users/sign_in'

  get 'welcome/index'

  match 'welcome/probe_list/:type' => 'welcome#probe_list', :via => [:get], :as => 'welcome_probe_list'
  get 'welcome/probe_list'

  match 'welcome/status/:source/:destination' => 'welcome#status', :via => [:get]

  get 'welcome/stats'

  match 'collect/id' => 'results#index'
  match 'collect/id/:destination_id/:metric_name/:dsmax/:dsmin/:dsavg/:sdmax/:sdmin/:sdavg/:timestamp/:uuid' => 'results#create',
        :via => [:get],
        :as => 'results_create',
        :constraints => { :destination_id => /\d+/,
                          :metric_name => /[a-z_]+/,
                          :dsmax => /[-]*[0-9]+[.]*[0-9]+/,
                          :dsmin => /[-]*[0-9]+[.]*[0-9]+/,
                          :dsavg => /[-]*[0-9]+[.]*[0-9]+/,
                          :sdmax => /[-]*[0-9]+[.]*[0-9]+/,
                          :sdmin => /[-]*[0-9]+[.]*[0-9]+/,
                          :sdavg => /[-]*[0-9]+[.]*[0-9]+/,
                          :timestamp => /\d+/,
                          :uuid => /[0-9A-Fa-f]+-[0-9A-Fa-f]+-[0-9A-Fa-f]+-[0-9A-Fa-f]+-[0-9A-Fa-f]+/
        }

  match 'collect/id/:destination_id/kpis/:cell_id/:brand/:model/:conn_type/:conn_tech/:signal/:error_rate/:change_of_ips/:route/:mtu/:dns_latency/:lac/:timestamp/:uuid' => 'kpi#create',
        :via => [:get],
        :as => 'kpi_create',
        :constraints => { :destination_id => /\d+/,
                          :cell_id => /[0-9\-]+/,
                          :brand => /.+/,
                          :model => /.+/,
                          :conn_type => /[A-Za-z+\-]+/,
                          :conn_tech => /[A-Za-z+\-]+/,
                          :signal => /[>|<|%3C|%3E]*[0-9.\- ]+|Desconhecido|unknown/,
                          :error_rate => /[>|<|%3C|%3E]*[0-9.\- ]+|Desconhecido|unknown'/,
                          :change_of_ips => /[0-9\-]+/,
                          :route => /.+/,
                          :mtu => /[0-9\-]+|Desconhecido/,
                          :dns_latency => /[%3C]*[0-9.\- ><]+|Desconhecido/,
                          :lac => /[0-9\-]+/,
                          :timestamp => /\d+/,
                          :uuid => /[0-9A-Fa-f]+-[0-9A-Fa-f]+-[0-9A-Fa-f]+-[0-9A-Fa-f]+-[0-9A-Fa-f]+/
        }

  match 'schedules/unused_profiles_form/:source_id/:destination_id' => 'schedules#unused_profiles_form',
        :constraints => {
            :source_id => /\d+/,
            :destination_id => /\d+/,
        }

  root :to => 'welcome#login'

end

app/models/metric.rb
# == Schema Information
#
# Table name: metrics
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  plugin      :string(255)
#  description :string(255)
#  reverse     :boolean
#  order       :integer
#  created_at  :timestamp(6)     not null
#  updated_at  :timestamp(6)     not null
#  view_unit   :string(255)
#  db_unit     :string(255)
#  metric_type :string(255)      default("active"), not null
#

class Metric < ActiveRecord::Base
  attr_accessible :description, :name, :order, :plugin, :reverse, :db_unit, :view_unit, :metric_type, :conversion_rate

  validates :name, :presence => true, :length => {:maximum => 30, :minimum => 3}, :uniqueness => true
  validates :plugin, :presence => true, :length => {:maximum => 20, :minimum => 3}, :uniqueness => true,
            :format => {:with => /[a-z0-9]+/}
  has_and_belongs_to_many :profiles
  has_many :thresholds
  before_save { |metric| 
    metric.view_unit ||= "unit"
    metric.db_unit ||= "unit"
    metric.conversion_rate = "1 #{self.raw_db_unit}".to_unit(self.raw_view_unit).scalar
    metric.order ||= Metric.highest_order+1
  }

  def db_unit
    self[:db_unit].to_s.gsub(/b\/s|B\/s/, 'b/s' => 'bps', 'B/s' => 'Bps')
  end

  def raw_db_unit
    self[:db_unit]
  end

  def db_unit= (value)
    self[:db_unit] = value.gsub(/bps|Bps/, 'bps' => 'b/s', 'Bps' => 'B/s')
  end

  def view_unit
    self[:view_unit].to_s.gsub(/b\/s|B\/s/, 'b/s' => 'bps', 'B/s' => 'Bps')
  end

  def raw_view_unit
    self[:view_unit]
  end

  def view_unit= (value)
    self[:view_unit] = value.gsub(/bps|Bps/, 'bps' => 'b/s', 'Bps' => 'B/s')
  end

  def metric_types
    [
        ['Métricas Ativas', 'active'],
        ['DNS', 'dns'],
        ['DNS Errors', 'dns_detail'],
        ['Eficiência DNS', 'dns_efficiency'],
        ['Carga Web', 'webload'],
        ['KPI', 'kpi'],
        ['Outra', '']
    ]
  end

  def search_metric_types(search_term)
    self.metric_types.each do |type|
      return type if type[1] == search_term
    end
  end

  def pretty_metric_type
    self.search_metric_types(self.metric_type)[0]
  end

  def pretty_scalar_convertion(result)
    "#{result} #{self.raw_db_unit}".to_unit(self.raw_view_unit).scalar
  end

  def pretty_human_reverse
    if self.reverse == true
      "Sim"
    else
      "Não"
    end
  end

  def self.highest_order_metric
    Metric.order("metrics.order DESC").limit(1).first
  end

  def self.highest_order
    self.highest_order_metric.order
  end

end

app/models/schedule.rb
# coding: utf-8
# == Schema Information
#
# Table name: schedules
#
#  id             :integer          not null, primary key
#  start          :timestamp(6)
#  end            :timestamp(6)
#  polling        :integer
#  status         :string(255)
#  created_at     :timestamp(6)     not null
#  updated_at     :timestamp(6)     not null
#  uuid           :string
#  destination_id :integer
#  source_id      :integer
#

class Schedule < ActiveRecord::Base
  before_save :default_values
  attr_accessible :end, :polling, :start, :status, :destination_id, :source_id, :profile_ids

  has_many :evaluations
  has_many :profiles, :through => :evaluations
  has_many :medians
  has_many :kpis

  accepts_nested_attributes_for :profiles
  belongs_to :destination, :class_name => 'Probe', :foreign_key => 'destination_id'
  belongs_to :source, :class_name => 'Probe', :foreign_key => 'source_id'

  validates_presence_of :destination_id, :source_id

  scope :active, where(:status => 1)
  scope :by_destination, proc { |destinations| where(:destination_id => destinations) unless destinations == '' or destinations[0] == '' }
  scope :by_source, proc { |sources| where(:source_id => sources) unless sources == '' or sources[0] == '' }

  def setup
    Yell.new(:gelf, :facility => 'netmetric').info 'Envio de parametros iniciado!',
                                                   '_schedule_id' => self.id
#W    self.profiles.each do |profile|
#W      require profile.config_method+'_job'
#W      Kernel.const_get((profile.config_method+'_job').camelize.to_sym).profile_setup(profile, self)
#W    end

    #TODO: tornar o carregamento da agenttable e managertable dinamico, quando tivermos a especificacao
#W    SnmpLegacyJob::agent_setup profiles, self
#W    SnmpLegacyJob::manager_setup profiles, self

    self.status = 'active'
    self.save
    Yell.new(:gelf, :facility => 'netmetric').info 'Envio de agenda de testes concluida!',
                                                   '_schedule_id' => self.id, '_probe_id' => self.destination.id
  end

  def allocated_profiles
    profiles = []
    if self.destination
      self.destination.schedules do |schedule|
        profiles += schedule.profiles
      end
    end

    profiles.uniq
  end

  def metrics (sort_by = :order)
    profiles = self.profiles
    metrics = []
    profiles.each do |profile|
      metrics += profile.metrics
    end
    #TODO: Gambiarra para colocar o thourhgput HTTP forcado
    if metrics.count
      metrics << Metric.find(3)
    end

    metrics.uniq.sort_by { |metric| metric[sort_by] }
  end

  def have_metric? (metric)
    self.metrics.include? metric
  end

  def default_values
#W  self.status ||= 'config'
    self.status ||= 'active'
    self.start ||= DateTime.now
    self.end ||= DateTime.now.advance(:years => +2).at_midnight
    self.uuid ||= SecureRandom.uuid.tr('-', '')
  end

  def pretty_status
    if self.status == 'active'
      "Ativo"
    else
      "Inativo"
    end
  end
end

app/controllers/schedules_controller.rb
# coding: utf-8
class SchedulesController < ApplicationController
  # GET /schedules
  # GET /schedules.json
  def index
    authorize! :read, self

    if request.format == 'html'
      @schedules = Schedule.paginate(:page => params[:page],
                                     :per_page => 15,
                                     :order => 'status')
    else
      @schedules = Schedule.order(:status).all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @schedules }
    end
  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show
    authorize! :read, self
    @schedule = Schedule.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @schedule }
    end
  end

  # GET /schedules/new
  # GET /schedules/new.json
  def new
    authorize! :manage, self
    @schedule = Schedule.new
    @connection_profile = ConnectionProfile.find(1)

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @schedule }
    end
  end

  # GET /schedules/1/edit
  def edit
    authorize! :manage, self
    @schedule = Schedule.find(params[:id])
  end

  # POST /schedules
  # POST /schedules.json
  def create
    authorize! :manage, self
    @schedule = Schedule.new(params[:schedule])

    respond_to do |format|
      if @schedule.save
        Yell.new(:gelf, :facility => 'netmetric').info 'Nova agenda configurada com sucesso.',
                                                       '_schedule_id' => @schedule.id, '_destination_name' => @schedule.destination.name,
                                                       '_source_name' => @schedule.source.name
        format.html { redirect_to @schedule, notice: 'Agenda programada com sucesso.' }
        format.json { render json: @schedule, status: :created, location: @schedule }
      else
        format.html { render action: 'new' }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /schedules/1
  # PUT /schedules/1.json
  def update
    authorize! :manage, self
    @schedule = Schedule.find(params[:id])

    respond_to do |format|
      if @schedule.update_attributes(params[:schedule])
        format.html { redirect_to @schedule, notice: 'Schedule was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    authorize! :manage, self
    @schedule = Schedule.find(params[:id])
    @schedule.destroy

    respond_to do |format|
      format.html { redirect_to schedules_url }
      format.json { head :no_content }
    end
  end

  def unused_profiles_form
    schedules = Schedule.where(:destination_id => params[:destination_id]).where(:source_id => params[:source_id]).all
    @connection_profile = Probe.find(params[:destination_id]).connection_profile
    @used_profiles = []
    schedules.each do |schedule|
      @used_profiles += schedule.profiles
    end
    @used_profiles = @used_profiles.uniq
    #WIRLAU - alterado provisoriamente para pegar todos os profiles
 #  @profiles = Profile.where(connection_profile_id: [@connection_profile.id,nil,""]).all
    @profiles = Profile.all;
    
    @unused_profiles = @profiles - @used_profiles

    render :layout => false
  end

  # Windows Schedules
  def win
    respond_to do |format|
      format.xml
    end
  end

  # Android / Linux Schedules
  def private_schedule
    ipaddress = params[:ipaddress]
    @probe = Probe.where(ipaddress: ipaddress).first

    @schedules = Schedule.where(destination_id: @probe.id).all

    respond_to do |format|
      format.xml
    end
  end

  # Android / Linux Schedules
  def private_agt_index
      ipaddress = params[:ipaddress]
      @probe = Probe.where(ipaddress: ipaddress).first;
      if @probe.nil?
	@probe_id = -1
      else
        @probe_id = @probe.id
      end
#     @schedules = Schedule.where(destination_id: @probe.id).all

      respond_to do |format|
          format.xml
      end
  end

end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_form.html.erb
<%= form_for(@schedule, :html => {:class => 'form-horizontal form-stop'}) do |f| %>
    <div class="row-fluid">
      <div class="span12">
        <div class="control-group">
          <%= f.label :source_id, 'Sonda de Origem', :class => 'control-label etooltip', 'data-title'.to_sym => 'Sonda que vai disparar as medições' %>
          <div class="controls">
            <%= f.collection_select :source_id, Probe.find_all_by_type('linux'), :id, :pretty_name %>
          </div>
        </div>
        <div class="control-group">
          <%= f.label :destination_id, 'Sonda de Destino', :class => 'control-label' %>
          <div class="controls">
            <%= f.collection_select :destination_id, Probe.all, :id, :pretty_name, :include_blank => "Selecione uma sonda..." %>
          </div>
        </div>
        <div id="unused_profiles">
          <div class="control-group">
            <label class="control-label" for="profiles">Perfis de Teste</label>
            <div class="controls" id="profiles">
              <div class="span3 alert alert-block">
                Selecione uma sonda de destino antes.
              </div>
            </div>
          </div>
        </div>
        <div class="alert alert-block">Aqui somente constam os perfis de teste que ainda não foram agendados. Não é permitido a superposição de testes.</div>
        <div class="control-group">
          <%= f.label :polling, 'Intervalo de Medição (minutos)', :class => 'control-label' %>
          <div class="controls">
            <%= f.number_field :polling, :placeholder => 'Intervalos >= 5 min' %>
          </div>
        </div>
        <div class="control-group">
          <div class="controls">
            <%= f.submit 'Salvar', :class => 'btn btn-primary btn-large' %>
            <%= link_to 'Voltar', schedules_path, :class => "btn btn-inverse btn-large " %>
          </div>
        </div>
      </div>
    </div>
<% end %>


<script type="text/javascript">
    $('.etooltip').tooltip();

    $("#schedule_destination_id").change(function (evt) {
        var destination_id = evt.currentTarget.value;
        var source_id =  $("#schedule_source_id").val();
        jQuery.ajax("<%=request.protocol+request.host_with_port+(url_for Schedule) %>/unused_profiles_form/"+source_id+"/"+destination_id,{
            success: function (data,status) {
                $("#unused_profiles").html(data);
            },
            dataType: 'html',
            headers: {
                'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
            }
        });
    });
</script>

app/views/schedules/edit.html.erb
<h1>Editando Agenda</h1>

<%= render 'form' %>

app/views/schedules/index.html.erb
<h2>Agendas e Testes</h2>
<div class="row-fluid">
  <div class="span12">
    <% if can? :create, User %>
        <div class="navbar">
          <div class="navbar-inner">
            <div class="span3 offset9">
              <%= link_to 'Novo Agendamento de Teste', new_schedule_url, :class => "btn btn-primary btn-block" %>
            </div>
          </div>
        </div>
    <% end %>
  </div>
</div>
<div class="row-fluid">
  <div class="span12">
    <table class="table table-bordered table-hover table-striped">
      <thead>
      <tr>
        <th>Sonda de Destino</th>
        <th>Perfil de Teste</th>
        <th>Sonda de Origem</th>
        <th>Polling</th>
        <th>Status</th>
        <th>Ações</th>
      </tr>
      </thead>
      <tbody>
      <% if @schedules.empty? %>
          <tr>
            <td colspan="7">Nenhum agendamento de teste encontrado com os critérios acima.</td>
          </tr>
      <% end %>
      <% @schedules.each do |schedule| %>
          <tr>
            <td><%= schedule.destination.name %>(<%= schedule.destination.ipaddress %>)</td>
            <td>
              <% schedule.profiles.each do |test_profile| %>
                  <span class="label label-info etooltip" data-title="<%= test_profile.name %>"><%= test_profile.name %></span>
              <% end %></td>
            <td><%= schedule.source.name %>(<%= schedule.source.ipaddress %>)</td>
            <td><%= schedule.polling %> min</td>
            <td><%= schedule.pretty_status %></td>
            <td><%= link_to 'Visualizar', schedule %></td>
            <td><%= link_to 'Editar', edit_schedule_path(schedule) if can? :edit, Schedule %></td>
            <td><%= link_to 'Excluir', schedule, method: :delete, data: {confirm: 'Você tem certeza que deseja excluir esta agenda?'} if can? :edit, Schedule %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
    <%= will_paginate @schedules, :style => 'color:#2C719B' %>
  </div>
</div>

app/views/schedules/new.html.erb
<h2>Nova Agenda de Testes</h2>
<%= render 'form' %>

app/views/schedules/private_agt_index.xml.erb
<agt-index><%= @probe_id %></agt-index> 

app/views/schedules/private_schedule.xml.erb
<% @schedules.each do |schedule| %>
    <schedule>
        <config>
            <uuid><%= schedule.uuid %></uuid>
        </config>
        <metrics>
            <% schedule.profiles.where(config_method: "http").each do |profile| %>
                <throughput_http>
                    <% cfg = ActiveSupport::JSON.decode(profile.config_parameters) %>
                    <download>
                        <numCon><%= cfg["download"]["numCon"] %></numCon>
                        <testTime><%= cfg["download"]["testTime"] %></testTime>
                        <path type="outro"><%= cfg["download"]["path"] %></path>
                    </download>
                    <upload>
                        <path><% cfg["upload"]["path"] %></path>
                        <file type="outro"><%= cfg["upload"]["file"] %></file>
                    </upload>
                </throughput_http>
            <% end %>
            <% schedule.profiles.where(config_method: "raw_xml").each do |profile| %>
                <%= profile.config_parameters %>
            <% end %>
            <% schedule.profiles.where(config_method: "dns").each do |profile| %>
                <dns>
                    <servers>
                        <% profile.nameservers.each do |ns| %>
                            <server><%= Nameserver.find(ns).address %></server>
                        <% end %>
                    </servers>
                    <urls>
                        <% profile.sites.each do |site| %>
                            <url><%= Site.find(site).url %></url>
                        <% end %>
                    </urls>
                </dns>
            <% end %>
            <% schedule.profiles.where(config_method: "url").each do |profile| %>
                <cargaWeb>
                    <urls>
                        <% profile.sites.each do |site| %>
                            <url><%= Site.find(site).url %></url>
                        <% end %>
                    </urls>
                </cargaWeb>
            <% end %>
        </metrics>
    </schedule>
<% end %>

app/views/schedules/show.html.erb
<h2> Visualização da Agenda e Teste</h2>
<div class="row-fluid">
    <p id="notice"><%= notice %></p>

    <p>
      <b>Início:</b>
      <%= @schedule.start %>
    </p>

    <p>
      <b>Fim:</b>
      <%= @schedule.end %>
    </p>

    <p>
      <b>Polling:</b>
      <%= @schedule.polling %>
    </p>

    <p>
      <b>Status:</b>
      <%= @schedule.status == "active"? "Ativo" : "Inativo" %>
    </p>

    <p>
      <b>Sonda de Origem:</b>
      <%= @schedule.source.name %>

      <b>Sonda de Destino:</b>
      <%= @schedule.destination.name %>
    </p>

    <p><b>Perfil de Teste/Métricas: </b></p>
    <div class="span12">
      <% @schedule.profiles.each do |test_profile| %>
      <div style="float:left; min-width:  120px">
        <span class="label label-info" data-title="<%= test_profile.name %>"><%= test_profile.name %></span>
          <ul>
          <% test_profile.metrics.each do |metric| %>
           <li> <%= metric.name %></li>
          <% end %>
          </ul>
      </div>
      <% end %>
    </div>

  <div class="">
    <div class="control-group" >
      <div class="controls">
        <%= link_to 'Editar', edit_schedule_path(@schedule), :class => "btn btn-primary btn-large " if can? :edit, Schedule  %>
        <%= link_to 'Voltar', schedules_path, :class => "btn btn-inverse btn-large " %>
      </div>
    </div>
  </div>
</div>

app/views/schedules/show.xml.erb
<schedule>
    <config>
        <uuid><%= @schedule.uuid %></uuid>
    </config>
    <metrics>
        <throughput_http>
            <download>
                <numCon>3</numCon>
                <testTime>2000</testTime>   //Valor em ms
                <path type="outro">http://143.54.85.34/files/httptest/arquivo_OUTROS_down</path>
                <path type="3G">http://143.54.85.34/files/httptest/arquivo_3G_down</path>
            </download>
            <upload>
                <path>http://143.54.85.34/handle_upload_1.php</path>
                <file type="outro">arquivo_OUTROS_up</file>
                <file  type="3G">arquivo_3G_up</file>
            </upload>
        </throughput_http>
        <dns>
            <servers>
                <server>200.204.135.240</server>
                <server>200.204.135.241</server>
            </servers>
            <urls>
                <url>http://www.g1.globo.com</url>
                <url>http://www.uol.com.br </url>
            </urls>
            <config>
                <timeout>2000</timeout> //Valor em ms
            </config>
        </dns>
        <cargaWeb>
            <urls>
                <url>http://www.vivo.com.br</url>
                <url>http://www.google.com.br</url>
            </urls>
        </cargaWeb>
        <sms>																			// Se for apenas teste pra ele mesmo, enviar “self” no lugar de um numero de telefone.
            <phoneNumber>4569</phoneNumber> //pode ter mais um de um telefone aqui
            <timeout>5</timeout>	//em segundos
        </sms>
    </metrics>
</schedule>

app/views/schedules/unused_profiles_form.html.erb
<div class="control-group">
  <label class="control-label" for="profiles">Perfis de Teste</label>
  <div class="controls" id="profiles">
    <% @unused_profiles.each do |unused_profile| %>
        <div class="span3">
          <label class="checkbox">
            <input type="checkbox" name="schedule[profile_ids][]" id="profile-<%=unused_profile.id%>"  value="<%= unused_profile.id %>" >
            <%= unused_profile.name.upcase %>
          </label>
          <% unused_profile.metrics.each do |metric| %>
              <span class="label label-info etooltip" data-title="<%= metric.description %>"><%= metric.name %><%= " (Anatel #{metric.thresholds.at(0).name})" if metric.thresholds.at(0) %></span>
          <% end %>
        </div>
    <% end %>
    <% if @profiles.empty? %>
        <div class="alert alert-error alert-block">
          Nenhum perfil de teste foi encontrado para o tipo de conexão <%= @connection_profile.name %>.<br>
          Você deve cadastrar perfis de teste para este tipo de conexão.
        </div>
    <% end %>
  </div>
</div>
<script type="text/javascript">
    $('.etooltip').tooltip();
</script>

app/views/schedules/win.xml.erb
<schedule>
	<config>
		<uuid></uuid>
	</config>
	<metrics>
		<throughput_http>
			<download>
				<numCon>3</numCon>
				<testTime>2000</testTime>
				<path type="outro">http://143.54.85.34/files/httptest/arquivo_OUTROS_down</path>
				<path type="3G">http://143.54.85.34/files/httptest/arquivo_3G_down</path>
			</download>
			<upload>
				<path>http://143.54.85.34/handle_upload_1.php</path>
				<file type="outro">arquivo_OUTROS_up</file>
				<file type="3G">arquivo_3G_up</file>
			</upload>
		</throughput_http>
		<dns>
			<servers>
				<server>200.204.135.240</server>
				<server>200.204.135.241</server>
			</servers>
			<urls>
				<url>http://www.g1.globo.com</url>
				<url>http://www.uol.com.br </url>
			</urls>
			<config>
				<timeout>2000</timeout> //Valor em ms
			</config>
		</dns>
		<cargaWeb>
			<urls>
				<url>http://www.vivo.com.br</url>
				<url>http://www.google.com.br</url>
			</urls>
		</cargaWeb>
	</metrics>
</schedule>