config/routes.rb
MomRails::Application.routes.draw do
  resources :sites

  resources :nameservers

  get 'route_reload' => 'welcome#route_reload'

  match 'reports' => 'reports#index', :as => 'reports'
  get 'reports/index', :as => 'index_reports'
  match 'reports/graph/:source_id/:destination_id/:metric_id' => 'reports#graph', :via => [:get]
  post 'reports/graph', :as =>'graph_reports'
  post 'reports/dygraphs_bruto', :as =>'dygraphs_bruto_reports'
  post 'reports/highcharts_bruto', :as =>'highcharts_bruto_reports'
  post 'reports/eaq_graph', :as =>'eaq_graph_reports'
  post 'reports/eaq_compliance_graph', :as =>'eaq_compliance_graph_reports'
  post 'reports/eaq_table', :as =>'eaq_table_reports'
  post 'reports/detail_eaq_table', :as =>'detail_eaq_table_reports'
  post 'reports/eaq2_table', :as => 'eaq2_table_reports'
  post 'reports/detail_eaq2_table', :as=> 'detail_eaq2_table_reports'
  post 'reports/detail_speed_type_eaq2_table', :as => 'detail_speed_type_eaq2_table_reports'
  post 'reports/detail_probe_eaq2_table', :as => 'detail_probe_eaq2_table_reports'
  post 'kpi/show' => 'kpi#show', :as => 'show_kpi'
  match 'reports/csv_bruto/:filename' => 'reports#csv_bruto', :as => 'reports_csv_bruto', :via => [:get]
  match 'reports/csv_diario/:filename' => 'reports#csv_diario', :as => 'reports_csv_diario', :via => [:get]
  match 'reports/csv_mensal/:filename' => 'reports#csv_mensal', :as => 'reports_csv_mensal', :via => [:get]
  match 'reports/xls_bruto/:filename' => 'reports#xls_bruto', :as => 'reports_xls_bruto', :via => [:get]
  match 'reports/xls_diario/:filename' => 'reports#xls_diario', :as => 'reports_xls_diario', :via => [:get]
  match 'reports/xls_mensal/:filename' => 'reports#xls_mensal', :as => 'reports_xls_mensal', :via => [:get]
  post 'reports/send' => 'reports#send_report', :as => 'send_reports'
  match 'reports/performance/:filename' => 'reports#performance', :as => 'reports_performance_export', :via => [:get]
  post 'reports/performance', :as => 'performance_reports'
  post 'reports/smartrate', :as => 'smartrate_reports'
  post 'reports/pacman', :as => 'pacman_reports'
  post 'reports/pacman_details', :as => 'pacman_details_reports'
  post 'reports/pacman_activity', :as => 'pacman_activity_reports'
  post 'reports/pacman_service_activity', :as => 'pacman_service_activity_reports'
  post 'reports/pacman_service_activity_details', :as => 'pacman_service_activity_details_reports'
  resources :metrics
  resources :tests
  resources :schedules
  get 'schedules/win/schedule' => 'schedules#win', :as => 'windows_schedules'
  post 'schedules/private_schedule' => 'schedules#private_schedule', :as => 'private_schedules'
  post 'schedules/private_agt_index' => 'schedules#private_agt_index', :as => 'private_agt_indexes'
  resources :probes do
    member do
      get 'destinations'
      get 'sources'

    end
  end

  post 'probes/load_location',:as=> 'probes_load_location'
  post 'probes/filter_uf', :as => 'probes_filter_uf'
  post 'probes/filter_destination', :as => 'probes_filter_destination'
  post 'probes/find_cns_by_state', :as => 'probes_find_cns_by_state'

  match 'probes/:id/metrics/:source_id' => 'probes#metrics', :via => [:get]
  match 'probes/:id/thresholds/:source_id' => 'probes#thresholds', :via => [:get]

  resources :metrics
  resources :process
  resources :profiles
  resources :dns_profiles
  resources :url_profiles
  resources :raw_xml_profiles
  resources :http_profiles

  resources :connection_profiles do
    resources :plans
  end
  resources :thresholds
  resources :plans

  devise_for :users #, :controllers => { :registrations => "registrations" }
  resources :users do
    get :active
  end
  as :user do
    put :update_password, :controller => :users
  end

  get 'users/sign_in'

  get 'welcome/index'

  match 'welcome/probe_list/:type' => 'welcome#probe_list', :via => [:get], :as => 'welcome_probe_list'
  get 'welcome/probe_list'

  match 'welcome/status/:source/:destination' => 'welcome#status', :via => [:get]

  get 'welcome/stats'

  match 'collect/id' => 'results#index'
  match 'collect/id/:destination_id/:metric_name/:dsmax/:dsmin/:dsavg/:sdmax/:sdmin/:sdavg/:timestamp/:uuid' => 'results#create',
        :via => [:get],
        :as => 'results_create',
        :constraints => { :destination_id => /\d+/,
                          :metric_name => /[a-z_]+/,
                          :dsmax => /[-]*[0-9]+[.]*[0-9]+/,
                          :dsmin => /[-]*[0-9]+[.]*[0-9]+/,
                          :dsavg => /[-]*[0-9]+[.]*[0-9]+/,
                          :sdmax => /[-]*[0-9]+[.]*[0-9]+/,
                          :sdmin => /[-]*[0-9]+[.]*[0-9]+/,
                          :sdavg => /[-]*[0-9]+[.]*[0-9]+/,
                          :timestamp => /\d+/,
                          :uuid => /[0-9A-Fa-f]+-[0-9A-Fa-f]+-[0-9A-Fa-f]+-[0-9A-Fa-f]+-[0-9A-Fa-f]+/
        }

  match 'collect/id/:destination_id/kpis/:cell_id/:brand/:model/:conn_type/:conn_tech/:signal/:error_rate/:change_of_ips/:route/:mtu/:dns_latency/:lac/:timestamp/:uuid' => 'kpi#create',
        :via => [:get],
        :as => 'kpi_create',
        :constraints => { :destination_id => /\d+/,
                          :cell_id => /[0-9\-]+/,
                          :brand => /.+/,
                          :model => /.+/,
                          :conn_type => /[A-Za-z+\-]+/,
                          :conn_tech => /[A-Za-z+\-]+/,
                          :signal => /[>|<|%3C|%3E]*[0-9.\- ]+|Desconhecido|unknown/,
                          :error_rate => /[>|<|%3C|%3E]*[0-9.\- ]+|Desconhecido|unknown'/,
                          :change_of_ips => /[0-9\-]+/,
                          :route => /.+/,
                          :mtu => /[0-9\-]+|Desconhecido/,
                          :dns_latency => /[%3C]*[0-9.\- ><]+|Desconhecido/,
                          :lac => /[0-9\-]+/,
                          :timestamp => /\d+/,
                          :uuid => /[0-9A-Fa-f]+-[0-9A-Fa-f]+-[0-9A-Fa-f]+-[0-9A-Fa-f]+-[0-9A-Fa-f]+/
        }

  match 'schedules/unused_profiles_form/:source_id/:destination_id' => 'schedules#unused_profiles_form',
        :constraints => {
            :source_id => /\d+/,
            :destination_id => /\d+/,
        }

  root :to => 'welcome#login'

end

app/controllers/probes_controller.rb
# coding: utf-8
class ProbesController < ApplicationController
  before_filter :authenticate_user!

  #escopos
  has_scope :by_city
  has_scope :by_state, :type => :array_or_string
  has_scope :by_type, :type => :array_or_string
  has_scope :by_pop, :type => :array_or_string
  has_scope :by_bras, :type => :array_or_string
  has_scope :is_anatel
  has_scope :by_modem, :type => :array_or_string
  has_scope :by_tech, :type => :array_or_string

  def index
    authorize! :read, self

    if request.format == 'html'
      @probes = apply_scopes(Probe).paginate(:page => params[:page],
                                             :per_page => 15,
                                             :order => 'name')
    else
      @probes = apply_scopes(Probe).order(:name).all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @probes }
    end
  end

  def show
    authorize! :read, self
    @probe = Probe.find(params[:id])
  end

  def new
    authorize! :manage, self
    @probe = Probe.new(params[:probe])

    begin
      @selected_plan = ConnectionProfile.find(params[:probe][:connection_profile_id]).plans
    rescue
      @selected_plan = ConnectionProfile.all.first.plans
    end

    respond_to do |format|
      format.json { render :json => @probe }
      format.xml { render :xml => @probe }
      format.html
    end
  end

  def edit
    authorize! :manage, self
    @probe = Probe.find(params[:id])

    begin
      @selected_plan = ConnectionProfile.find(params[:probe][:connection_profile_id]).plans
    rescue
      @selected_plan = ConnectionProfile.all.first.plans
    end
  end

  def create
    authorize! :manage, self
    @probe = Probe.new(params[:probe])

    @connection_profile = ConnectionProfile.find(params[:probe][:connection_profile_id])
    @probe.connection_profile = @connection_profile

    @plan = Plan.find(params[:probe][:plan_id])
    @probe.plan = @plan

    begin
      @selected_plan = ConnectionProfile.find(params[:probe][:connection_profile_id]).plans
    rescue
      @selected_plan = ConnectionProfile.all.first.plans
    end

    if @probe.save
      Probe.add_pop @probe.pop unless @probe.pop.nil?
      Probe.add_modem @probe.modem unless @probe.modem.nil?
      Probe.add_bras @probe.bras unless @probe.bras.nil?
      respond_to do |format|
        format.json { render :json => @probe.to_json, :status => 200 }
        format.xml { head :ok }
        format.html { redirect_to @probe, notice: 'Suas alterações foram salvas com sucesso.' }
      end
    else
      respond_to do |format|
        format.json { render :text => "Sonda não pode ser criado.", :status => :unprocessable_entity } # placeholder
        format.xml { head :ok }
        format.html { render :action => :new, :status => :unprocessable_entity }
      end
    end
  end

  def update
    authorize! :manage, self
    @probe = Probe.find(params[:id])

    begin
      @selected_plan = ConnectionProfile.find(params[:probe][:connection_profile_id]).plans
    rescue
      @selected_plan = ConnectionProfile.all.first.plans
    end

    respond_to do |format|
      if @probe.update_attributes(params[:probe])
        Probe.add_pop @probe.pop unless @probe.pop.nil?
        Probe.add_modem @probe.modem unless @probe.modem.nil?
        Probe.add_bras @probe.bras unless @probe.bras.nil?
        format.html { redirect_to probes_path, notice: 'Suas alterações foram salvas com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @probe.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize! :manage, self
  end

  def sources
    probe = Probe.find(params[:id])

    respond_to do |format|
      format.json { render :json => probe.sources, :status => 200 }
    end
  end

  def destinations
    probe = Probe.find(params[:id])

    respond_to do |format|
      format.json { render :json => probe.destinations, :status => 200 }
    end
  end

  def metrics
    source = Probe.find(params[:source_id])
    destination = Probe.find(params[:id])

    metrics = destination.metrics(source).select { |metric| metric.metric_type == 'active' }

    respond_to do |format|
      format.json { render :json => metrics, :status => 200 }
    end
  end

  def thresholds
    source = Probe.find(params[:source_id])
    destination = Probe.find(params[:id])

    thresholds = destination.thresholds(source)

    respond_to do |format|
      format.json { render :json => thresholds, :status => 200 }
    end
  end

  def load_location
    probe = Probe.all

    respond_to do |format|
      format.json { render :json => probe, :status => 200 }
    end
  end

  def filter_uf
    uf = params[:uf]
    cod_uf = Array.new
    Probe.states.each do |state|
      uf.each do |uf|
        if state.at(1) == uf
          cod_uf << state.at(1)
        end
      end
    end

    cods = Array.new
    cod_uf.each do |ufs|
      Probe.cns.each do |cod_n|
        if ufs == cod_n.at(0).downcase
          cods << cod_n.at(1)
        end
      end
    end

    respond_to do |format|
      format.json { render :json => cods }
    end
  end

  def filter_destination
    uf = params[:uf]
    dest_uf = Array.new
    Probe.states.each do |state|
      uf.each do |uf|
        if state.at(1) == uf
          dest_uf << state.at(1)
        end
      end
    end

    destinations = Array.new
    dest_uf.each do |ufs|
      Probe.all.each do |p|
        if ufs == p.state.downcase
          destinations << p
        end
      end
    end

    respond_to do |format|
      format.json { render :json => destinations }
    end
  end

  def bras
    respond_to do |format|
      format.json { render :json => Probe.brass }
    end
  end

  def find_cns_by_state
    respond_to do |format|
      format.json { render :json => Probe.find_cns_by_state(params[:state]) }
    end
  end

end

app/helpers/probes_helper.rb
module ProbesHelper
end

app/views/probes/create.html.erb
<h1>Probes#create</h1>
<p>Find me in app/views/probes/create.html.erb</p>

app/views/probes/destroy.html.erb
<h1>Probes#destroy</h1>
<p>Find me in app/views/probes/destroy.html.erb</p>

app/views/probes/edit.html.erb
<div class="row-fluid">
  <h2>Editando a sonda <%= @probe.name %> (#<%= @probe.id %>)</h2>
  <h4>Dados obrigatórios</h4>
  <%= form_for @probe, :html => {:class => "form-horizontal"} do |f| %>
      <div class="span12">
        <div class="control-group">
          <%= f.label :type, "Tipo da Sonda", :class => "control-label" %>
          <div class="controls">
            <%= f.select :type, Probe.types %>
          </div>
        </div>
        <div class="control-group">
          <%= f.label :ipaddress, "Endereço IP", :class => "control-label" %>
          <div class="controls">
            <span style="line-height: 30px"><%= @probe.ipaddress %></span>
          </div>
        </div>
        <div class="control-group">
          <%= f.label :pre_address, "Endereço", :class => "control-label", "data-provide".to_sym => "typeahead" %>
          <div class="controls">
            <%= f.text_field :pre_address, :placeholder => "O endereço pode ser qualquer parte (rua, CEP, cidade, bairro), igual ao Google Maps", :class => "span8" %>
          </div>
        </div>
        <div class="control-group">
          <%= f.label :name, "Nome da sonda", :class => "control-label" %>
          <div class="controls">
            <%= f.text_field :name, :placeholder => "Nome da sonda" %>
          </div>
        </div>
        <div class="control-group">
          <%= f.label :cn, "Código de Área", :class => "control-label" %>
          <div class="controls">
            <%= f.select :cn, Probe.find_cns_by_state(@probe.state) %>
          </div>
        </div>
        <div class="control-group">
          <%= f.label :connection_profile_id, "Conexão / Plano", :class => "control-label" %>
          <div class="controls">
            <%= f.collection_select :connection_profile_id, ConnectionProfile.all, :id, :name %>
            <%= f.collection_select :plan_id, @selected_plan, :id, :name_with_throughput, {}, :class => "span4" %>
          </div>
        </div>
      </div>
      <h4>Dados extras</h4>

      <div class="span12">
        <div class="control-group">
          <%= f.label :bras, "BRAS", :class => "control-label" %>
          <div class="controls">
            <%= f.text_field :bras, :placeholder => "Aplicável ao Speedy, ex: BRAS_ER01" %>
          </div>
        </div>
        <div class="control-group">
          <%= f.label :pop, "POP", :class => "control-label" %>
          <div class="controls">
            <%= f.text_field :pop, :placeholder => "Aplicável ao Speedy, ex: POPGR" %>
          </div>
        </div>
        <div class="alert">
          <strong>Atenção!</strong> Altere somente os dados abaixo em caso de necessidade.
          <em>Por exemplo, medição feita por GPS</em>
        </div>
        <div class="control-group">
          <%= f.label :latitude, "Latitude / Longitude", :class => "control-label" %>
          <div class="controls">
            <%= f.text_field :latitude, :placeholder => "Latitude" %>
            <%= f.text_field :longitude, :placeholder => "Longitude" %>
          </div>
        </div>
        <div class="control-group">
          <%= f.label :city, "Cidade / UF", :class => "control-label" %>
          <div class="controls">
            <%= f.text_field :city, :placeholder => "Cidade" %>
            <%= f.select :state, Probe.states %>
          </div>
        </div>
        <div class="control-group">
          <%= f.label :address, "Endereço após ajustes", :class => "control-label" %>
          <div class="controls">
            <%= f.text_field :address, :placeholder => "Endereço após ajustes do sistema", :class => "span8" %>
          </div>
        </div>
        <div class="control-group">
          <div class="controls">
            <%= f.submit "Salvar", :class => "btn btn-primary btn-large" %>
          </div>
        </div>
      </div>
  <% end %>
</div>
<script type="text/javascript">
    var service = new google.maps.places.AutocompleteService({componentRestrictions: {country: 'br'}});
    var geocoder = new google.maps.Geocoder();
    var results2;

    function mapsComponentByType(results, type, short_name, space) {
        var retorno = "";
        for (var i = 0; i < results[0].address_components.length; i++) {
            var addr = results[0].address_components[i];
            if (addr.types[0] == type) {
                if (space) retorno += space;
                if (short_name)
                    switch (addr.short_name) {
                        case "São Paulo":
                            retorno += "sp";
                            break;
                        default:
                            retorno += addr.short_name;
                    }
                else
                    retorno += addr.long_name;
            }

        }
        return retorno;
    }

    $("#probe_pre_address").typeahead({
        source: function (query, process) {
            service.getPlacePredictions({ input: query }, function (predictions, status) {
                if (status == google.maps.places.PlacesServiceStatus.OK) {
                    process($.map(predictions, function (prediction) {
                        return prediction.description;
                    }));
                }
            });
        },
        updater: function (item) {
            geocoder.geocode({ address: item }, function (results, status) {
                if (status != google.maps.GeocoderStatus.OK) {
                    alert('Endereço não pode ser obtido, Google Maps emitiu erro');
                    return;
                }
                $("#probe_latitude").val(results[0].geometry.location.lat());
                $("#probe_longitude").val(results[0].geometry.location.lng());
                $("#probe_city").val(mapsComponentByType(results, "locality"));
                $("#probe_state").val(mapsComponentByType(results, "administrative_area_level_1", true).toLowerCase());
                $("#probe_state").trigger('change');
                var editedAddress = jQuery.trim(mapsComponentByType(results, "route") + mapsComponentByType(results, "street_number", false, ", ") + mapsComponentByType(results, "sublocality", false, ", "));
                editedAddress = jQuery.trim(editedAddress.replace(/^,|,$/g, ''));
                $("#probe_address").val(editedAddress);
                var nome = mapsComponentByType(results, "administrative_area_level_1", true) + "-" + mapsComponentByType(results, "locality") + mapsComponentByType(results, "sublocality", false, "-");
                nome = nome.replace(/ /g, "_");
                $("#probe_name").val(nome.toLowerCase());
                console.log(results[0]);
            });
            return item;
        },
        minLength: 4
    });

    $("#probe_connection_profile_id").change(function (evt) {
        var connProfileID = evt.currentTarget.value;
        jQuery.ajax("<%=request.protocol+request.host_with_port+(url_for ConnectionProfile) %>/" + connProfileID + "/plans", {
            success: function (data, status) {
                $("#probe_plan_id").html("");
                jQuery.each(data, function (i, plan) {
                    $("#probe_plan_id").append('<option value=\"' + plan.id + "\">" + plan.name + " (" + plan.throughputDown + "/" + plan.throughputUp + ")</option>")
                });
            },
            dataType: 'json',
            headers: {
                'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
            }
        });
    });

    $('#probe_bras').typeahead({
        source: <%=Probe.brass.to_json.html_safe %>
    });

    $('#probe_pop').typeahead({
        source: <%=Probe.pops.to_json.html_safe %>
    });

    $('.etooltip').tooltip();

    $('#probe_state').change(function (evt) {
        var estado = jQuery(evt.currentTarget).val();

        jQuery.post('<%=probes_find_cns_by_state_url%>', { state: estado }).done(function (dataReturned) {

            $('#probe_cn').attr('disabled', false);
            $('#probe_cn').children('option').remove();

            var strOptionscn = "";
            $.each(dataReturned, function (i, data) {
                strOptionscn += "<option value=\"" + data[0] + "\">" + data[1] + "</option>";
            });

            $('#probe_cn').append(strOptionscn);

        });
    });

</script>

app/views/probes/index.html.erb
<h3>Sondas de teste (Agentes)</h3>
<div class="row-fluid">
  <div class="span10">
    <div class="navbar">
      <div class="navbar-inner">
        <div class="span10">
          <%= form_tag nil, :class => "navbar-form form-inline", :method => :get do %>
              <label for="probe-type" class="filter-bar">Tipo da sonda:</label>
              <select name="by_type" id="probe-type" class="span2">
                <option value="">Todas</option>
                <% Probe.types.each_with_index do |type, index| %>
                    <option value="<%= type.at(1) %>" <%= params[:by_type].to_s == type.at(1).to_s ? "selected=\"selected\"".html_safe : "" %>><%= type.at(0) %></option>
                <% end %>
              </select>
              <label for="probe-city" class="filter-bar">Cidade:</label>
              <input type="text" name="by_city" id="probe-city" class="span3" value="<%= params[:by_city].to_s %>">
              <label for="probe-type" class="filter-bar">UF:</label>
              <select name="by_state" id="probe-state" class="span2">
                <option value="">Todas</option>

                <% Probe.states.each do |state| %>
                    <option value="<%= state.at(1) %>" <%= params[:by_state].to_s == state.at(1).to_s ? "selected=\"selected\"".html_safe : "" %>><%= state.at(1).upcase %></option>
                <% end %>
              </select>
              <button type="submit" class="btn">Filtrar!</button>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="span2">
    <div class="navbar">
      <div class="navbar-inner">
        <%= link_to "Nova Sonda", new_probe_path, :class => "btn btn-primary btn-block" %>
      </div>
    </div>
  </div>
</div>
<div class="row-fluid">
  <div class="span12">
    <table class="table table-bordered table-hover table-striped">
      <thead>
      <tr>
        <th>Nome</th>
        <th>Hostname</th>
        <th>Cidade</th>
        <th>UF</th>
        <th>Conexão / Plano</th>
        <th>Ult. Atualização</th>
        <th>Versão</th>
        <th>Status</th>
        <th colspan="3">Ações</th>
      </tr>
      </thead>
      <tbody>
      <% if @probes.empty? %>
          <tr>
            <td colspan="7">Nenhuma sonda encontrada com os critérios acima.</td>
          </tr>
      <% end %>
      <% @probes.each do |probe| %>
          <tr>
            <td>
              <%= image_tag "icons/"+probe.type+"16.png" %>
              <%= link_to probe.name, probe %>
            </td>
            <td><%= link_to probe.ipaddress, probe %></td>
            <td><%= probe.city %></td>
            <td><%= probe.state.upcase %></td>
            <td><%= probe.connection_profile.name %> / <%= probe.plan.name %></td>
            <td><%= probe.updated_at.to_datetime %></td>
            <td><%= probe.agent_version.nil? ? '-' : probe.agent_version %>
              /<%= probe.osversion.nil? ? '-' : probe.osversion %></td>
            <td><%= probe.pretty_status.capitalize %></td>
            <td><%= link_to 'Visualizar', probe %></td>
            <td><%= link_to "Editar", edit_probe_path(probe) if can? :edit, Probe %></td>
            <td><%= link_to 'Excluir', probe, method: :delete, data: {confirm: 'Você tem certeza que deseja excluir este Agente?'} if can? :edit, Probe %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
    <%= will_paginate @probes, :style => 'color:#2C719B' %>
  </div>
</div>

app/views/probes/show.html.erb
<%= javascript_include_tag "gmap/gmap3" %>

<h2>Visualização da Sonda <%= @probe.name %> (#<%= @probe.id %>)</h2>
<div class="row-fluid">
  <div class="span7">
    <p>
      <b>Status:</b>
      <%= @probe.pretty_status %>
    </p>

    <p>
      <b>Tipo da sonda:</b>
      <%= @probe.type.humanize %>
    </p>

    <p>
      <b>Hostname:</b>
      <%= @probe.ipaddress %>
    </p>

    <p>
      <b>Endereço:</b>
      <%= @probe.address %>
    </p>

    <p>
      <b>Cidade/UF:</b>
      <%= @probe.city %>/<%= @probe.state.upcase %>
    </p>

    <p>
      <b>Código de Área:</b>
      <%= @probe.cn %>
    </p>

    <p>
      <b>Conexão:</b>
      <%= @probe.connection_profile.name %>
    </p>

    <p>
      <b>Plano:</b>
      <%= @probe.plan.name_with_throughput %>
    </p>

    <p>
      <b>Lat/Lon:</b>
      <%= @probe.latitude %> / <%= @probe.longitude %>
    </p>

    <p>
      <b>Endereço IP:</b>
      <%= @probe.real_ipaddress %> às <%= DateTime.now %>
    </p>

    <div class="control-group">
      <div class="controls">
        <%= link_to 'Editar', edit_probe_path(@probe), :class => "btn btn-primary btn-large " if can? :edit, Schedule %>
        <%= link_to 'Voltar', probes_path, :class => "btn btn-inverse btn-large " %>
      </div>
    </div>
  </div>

  <div class="span4">
    <div id="specMap" class="googleMap"></div>
  </div>


</div>

<!-- Localização do agente no Mapa -->
<script type="text/javascript">

    function loadProbe(lat, lng, type) {
        //  {lat:
        <%= @probe.latitude %>, lng:
        <%= @probe.longitude %>, options:{icon:'
        <%= asset_path("icons/pin_green.png")%>'}}
        if (type == "linux")
            return [
                {lat: lat, lng: lng, options: {icon: '<%= asset_path("icons/pin_linux.png")%>'}}
            ]
        else
            return [
                {lat: lat, lng: lng, options: {icon: '<%= asset_path("icons/pin_android.png")%>'}}
            ]

    }

    $(function () {
        $("#specMap").gmap3({
            map: {
                options: {
                    center: [<%= @probe.latitude %>, <%= @probe.longitude %>],
                    zoom: 14,
                    zoomControl: true,
                    zoomControlOptions: {
                        style: google.maps.ZoomControlStyle.LARGE
                    },
                    panControl: true,
                    mapTypeControl: true,
                    mapTypeControlOptions: {
                        style: google.maps.MapTypeControlStyle.DROPDOWN_MENU
                    },
                    navigationControl: false,
                    scrollwheel: true,
                    streetViewControl: false
                }
            },
            marker: {
                values: loadProbe(<%= @probe.latitude %>, <%= @probe.longitude %>, '<%= @probe.type %>')

            }
        });
    });
</script>

app/views/probes/update.html.erb
<h1>Probes#update</h1>
<p>Find me in app/views/probes/update.html.erb</p>