config/routes.rb
MomRails::Application.routes.draw do
  resources :sites

  resources :nameservers

  get 'route_reload' => 'welcome#route_reload'

  match 'reports' => 'reports#index', :as => 'reports'
  get 'reports/index', :as => 'index_reports'
  match 'reports/graph/:source_id/:destination_id/:metric_id' => 'reports#graph', :via => [:get]
  post 'reports/graph', :as =>'graph_reports'
  post 'reports/dygraphs_bruto', :as =>'dygraphs_bruto_reports'
  post 'reports/highcharts_bruto', :as =>'highcharts_bruto_reports'
  post 'reports/eaq_graph', :as =>'eaq_graph_reports'
  post 'reports/eaq_compliance_graph', :as =>'eaq_compliance_graph_reports'
  post 'reports/eaq_table', :as =>'eaq_table_reports'
  post 'reports/detail_eaq_table', :as =>'detail_eaq_table_reports'
  post 'reports/eaq2_table', :as => 'eaq2_table_reports'
  post 'reports/detail_eaq2_table', :as=> 'detail_eaq2_table_reports'
  post 'reports/detail_speed_type_eaq2_table', :as => 'detail_speed_type_eaq2_table_reports'
  post 'reports/detail_probe_eaq2_table', :as => 'detail_probe_eaq2_table_reports'
  post 'kpi/show' => 'kpi#show', :as => 'show_kpi'
  match 'reports/csv_bruto/:filename' => 'reports#csv_bruto', :as => 'reports_csv_bruto', :via => [:get]
  match 'reports/csv_diario/:filename' => 'reports#csv_diario', :as => 'reports_csv_diario', :via => [:get]
  match 'reports/csv_mensal/:filename' => 'reports#csv_mensal', :as => 'reports_csv_mensal', :via => [:get]
  match 'reports/xls_bruto/:filename' => 'reports#xls_bruto', :as => 'reports_xls_bruto', :via => [:get]
  match 'reports/xls_diario/:filename' => 'reports#xls_diario', :as => 'reports_xls_diario', :via => [:get]
  match 'reports/xls_mensal/:filename' => 'reports#xls_mensal', :as => 'reports_xls_mensal', :via => [:get]
  post 'reports/send' => 'reports#send_report', :as => 'send_reports'
  match 'reports/performance/:filename' => 'reports#performance', :as => 'reports_performance_export', :via => [:get]
  post 'reports/performance', :as => 'performance_reports'
  post 'reports/smartrate', :as => 'smartrate_reports'
  post 'reports/pacman', :as => 'pacman_reports'
  post 'reports/pacman_details', :as => 'pacman_details_reports'
  post 'reports/pacman_activity', :as => 'pacman_activity_reports'
  post 'reports/pacman_service_activity', :as => 'pacman_service_activity_reports'
  post 'reports/pacman_service_activity_details', :as => 'pacman_service_activity_details_reports'
  resources :metrics
  resources :tests
  resources :schedules
  get 'schedules/win/schedule' => 'schedules#win', :as => 'windows_schedules'
  post 'schedules/private_schedule' => 'schedules#private_schedule', :as => 'private_schedules'
  post 'schedules/private_agt_index' => 'schedules#private_agt_index', :as => 'private_agt_indexes'
  resources :probes do
    member do
      get 'destinations'
      get 'sources'

    end
  end

  post 'probes/load_location',:as=> 'probes_load_location'
  post 'probes/filter_uf', :as => 'probes_filter_uf'
  post 'probes/filter_destination', :as => 'probes_filter_destination'
  post 'probes/find_cns_by_state', :as => 'probes_find_cns_by_state'

  match 'probes/:id/metrics/:source_id' => 'probes#metrics', :via => [:get]
  match 'probes/:id/thresholds/:source_id' => 'probes#thresholds', :via => [:get]

  resources :metrics
  resources :process
  resources :profiles
  resources :dns_profiles
  resources :url_profiles
  resources :raw_xml_profiles
  resources :http_profiles

  resources :connection_profiles do
    resources :plans
  end
  resources :thresholds
  resources :plans

  devise_for :users #, :controllers => { :registrations => "registrations" }
  resources :users do
    get :active
  end
  as :user do
    put :update_password, :controller => :users
  end

  get 'users/sign_in'

  get 'welcome/index'

  match 'welcome/probe_list/:type' => 'welcome#probe_list', :via => [:get], :as => 'welcome_probe_list'
  get 'welcome/probe_list'

  match 'welcome/status/:source/:destination' => 'welcome#status', :via => [:get]

  get 'welcome/stats'

  match 'collect/id' => 'results#index'
  match 'collect/id/:destination_id/:metric_name/:dsmax/:dsmin/:dsavg/:sdmax/:sdmin/:sdavg/:timestamp/:uuid' => 'results#create',
        :via => [:get],
        :as => 'results_create',
        :constraints => { :destination_id => /\d+/,
                          :metric_name => /[a-z_]+/,
                          :dsmax => /[-]*[0-9]+[.]*[0-9]+/,
                          :dsmin => /[-]*[0-9]+[.]*[0-9]+/,
                          :dsavg => /[-]*[0-9]+[.]*[0-9]+/,
                          :sdmax => /[-]*[0-9]+[.]*[0-9]+/,
                          :sdmin => /[-]*[0-9]+[.]*[0-9]+/,
                          :sdavg => /[-]*[0-9]+[.]*[0-9]+/,
                          :timestamp => /\d+/,
                          :uuid => /[0-9A-Fa-f]+-[0-9A-Fa-f]+-[0-9A-Fa-f]+-[0-9A-Fa-f]+-[0-9A-Fa-f]+/
        }

  match 'collect/id/:destination_id/kpis/:cell_id/:brand/:model/:conn_type/:conn_tech/:signal/:error_rate/:change_of_ips/:route/:mtu/:dns_latency/:lac/:timestamp/:uuid' => 'kpi#create',
        :via => [:get],
        :as => 'kpi_create',
        :constraints => { :destination_id => /\d+/,
                          :cell_id => /[0-9\-]+/,
                          :brand => /.+/,
                          :model => /.+/,
                          :conn_type => /[A-Za-z+\-]+/,
                          :conn_tech => /[A-Za-z+\-]+/,
                          :signal => /[>|<|%3C|%3E]*[0-9.\- ]+|Desconhecido|unknown/,
                          :error_rate => /[>|<|%3C|%3E]*[0-9.\- ]+|Desconhecido|unknown'/,
                          :change_of_ips => /[0-9\-]+/,
                          :route => /.+/,
                          :mtu => /[0-9\-]+|Desconhecido/,
                          :dns_latency => /[%3C]*[0-9.\- ><]+|Desconhecido/,
                          :lac => /[0-9\-]+/,
                          :timestamp => /\d+/,
                          :uuid => /[0-9A-Fa-f]+-[0-9A-Fa-f]+-[0-9A-Fa-f]+-[0-9A-Fa-f]+-[0-9A-Fa-f]+/
        }

  match 'schedules/unused_profiles_form/:source_id/:destination_id' => 'schedules#unused_profiles_form',
        :constraints => {
            :source_id => /\d+/,
            :destination_id => /\d+/,
        }

  root :to => 'welcome#login'

end

app/models/report.rb
# == Schema Information
#
# Table name: reports
#
#  id         :integer          not null, primary key
#  user       :string(255)
#  uuid       :string
#  timestamp  :datetime
#  agent_type :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Report < ActiveRecord::Base
  attr_accessible :agent_type, :timestamp, :user, :uuid
end

app/controllers/reports_controller.rb
# coding: utf-8
class ReportsController < ApplicationController
  #escopos
  has_scope :by_city
  has_scope :by_state, :type => :array_or_string
  has_scope :by_type, :type => :array_or_string
  has_scope :by_pop, :type => :array_or_string
  has_scope :by_bras, :type => :array_or_string
  has_scope :is_anatel
  has_scope :by_modem, :type => :array_or_string
  has_scope :by_tech, :type => :array_or_string
  has_scope :by_conn_type, :type => :array_or_string
  #variaveis globais
  attr_accessor :smartrate_dns_total, :smartrate_dns_results

  def index
    @report_types = [
        ['Gráfico de Indicadores Anatel/EAQ - Consolidação Diária', 'eaq_graph'],
        ['Gráfico de Indicadores Anatel/EAQ - Consolidação Mensal', 'eaq_compliance_graph'],
        ['Gráfico de Dados Brutos', 'graph'],
        ['Tabela de Indicadores Anatel/EAQ', 'eaq_table']
    ]
  end

  def graph
    source = Probe.find(params[:source][:id])
    destination = Probe.find(params[:destination][:id])
    metric = Metric.find(params[:metric][:id])
    schedule = Schedule.where(:destination_id => destination.id).where(:source_id => source.id).all.last

    from = DateTime.parse(params[:date][:start]+' '+params[:time][:start]+' '+DateTime.current.zone).in_time_zone
    to = DateTime.parse(params[:date][:end]+' '+params[:time][:end]+' '+DateTime.current.zone).in_time_zone

    raw_results = Results.
        where(:schedule_id => schedule.id).
        where(:metric_id => metric.id).
        where(:timestamp => from..to).order('timestamp ASC').all

    results = []

    if metric.plugin != 'rtt'
      raw_results.each do |raw_result|
        results << {
            :x => raw_result.timestamp,
            :dsavg => raw_result.dsavg,
            :sdavg => raw_result.sdavg,
            :dsmin => raw_result.dsmin,
            :dsmax => raw_result.dsmax,
            :sdmin => raw_result.sdmin,
            :sdmax => raw_result.sdmax,
            :extra => {:uuid => raw_result.uuid}
        }
      end
    else
      raw_results.each do |raw_result|
        results << {
            :x => raw_result.timestamp,
            :dsavg => raw_result.dsavg,
            :dsmin => raw_result.dsmin,
            :dsmax => raw_result.dsmax,
            :extra => {:uuid => raw_result.uuid}
        }
      end
    end

    data = {
        :source => source,
        :destination => destination,
        :metric => metric,
        :schedule => schedule,
        :range => {:start => from, :end => to},
        :results => results
    }

    respond_to do |format|
      format.json { render :json => data, :status => 200 }
    end
  end

  def eaq2_table
    @uid = SecureRandom.uuid #id necessario para div
    @from = DateTime.parse(params[:date][:start])
    @to = DateTime.parse(params[:date][:end])
    @months = @from.all_months_until @to
    @months[0] = Date.parse(@from.to_s)
    @type = params[:agent] # android or linux
    @agent_type = params[:agent_type] # fixed or mobile, if linux
    @states = params[:state]
    @cn = params[:cn]
    @goal_filter = params[:goal_filter] #all,above or under
    @pop = params[:pop]
    @bras = params[:bras]


    if @type.include? "all"
      @type = ["android", "linux"]
      @agent_type = ["fixed", "mobile"]
    end


    if @agent_type.nil?
      @agent_type = ["fixed", "mobile"]
    end

    if @goal_filter.nil?
      @goal_filter = false
    end

    if @bras.nil?
      @bras = 'all'
    end

    # Garantir que não tenhamos nulos
    @cn.delete("")
    @states.delete("")

    if @agent_type.include? 'fixed'
      fixed_conn_profile = ConnectionProfile.
          where(:conn_type => "fixed")
    else
      fixed_conn_profile = nil
    end

    if @agent_type.include? 'mobile'
      mobile_conn_profile = ConnectionProfile.
          where(:conn_type => "mobile")
    else
      mobile_conn_profile = nil
    end

    if !(@pop.include? 'all') && !(@bras.include? 'all')
      fixed_probes = Probe.
          where(:connection_profile_id => fixed_conn_profile).
          where(:state => @states).
          where(:areacode => @cn).
          where(:type => @type).
          where(:anatel => @goal_filter).
          where(:pop => @pop).
          where(:bras => @bras)

      mobile_probes = Probe.
          where(:connection_profile_id => mobile_conn_profile).
          where(:state => @states).
          where(:areacode => @cn).
          where(:type => @type).
          where(:anatel => @goal_filter).
          where(:pop => @pop).
          where(:bras => @bras)

    else
      if (@pop.include? 'all') && (@bras.include? 'all')
        fixed_probes = Probe.
            where(:connection_profile_id => fixed_conn_profile).
            where(:state => @states).
            where(:areacode => @cn).
            where(:type => @type).
            where(:anatel => @goal_filter)

        mobile_probes = Probe.
            where(:connection_profile_id => mobile_conn_profile).
            where(:state => @states).
            where(:areacode => @cn).
            where(:type => @type).
            where(:anatel => @goal_filter)

        all_probes = Probe.
            where(:state => @states).
            where(:areacode => @cn).
            where(:type => @type).
            where(:anatel => @goal_filter).
            by_conn_type(@agent_type)
      else
        if @pop.include? 'all'
          fixed_probes = Probe.
              where(:connection_profile_id => fixed_conn_profile).
              where(:state => @states).
              where(:areacode => @cn).
              where(:type => @type).
              where(:anatel => @goal_filter).
              where(:bras => @bras)

          mobile_probes = Probe.
              where(:connection_profile_id => mobile_conn_profile).
              where(:state => @states).
              where(:areacode => @cn).
              where(:type => @type).
              where(:anatel => @goal_filter).
              where(:bras => @bras)

          all_probes = Probe.
              where(:state => @states).
              where(:areacode => @cn).
              where(:type => @type).
              where(:anatel => @goal_filter).
              where(:bras => @bras).
              by_conn_type(@agent_type)

        else
          if @bras.include? 'all'
            fixed_probes = Probe.
                where(:connection_profile_id => fixed_conn_profile).
                where(:state => @states).
                where(:areacode => @cn).
                where(:type => @type).
                where(:anatel => @goal_filter).
                where(:pop => @pop)

            mobile_probes = Probe.
                where(:connection_profile_id => mobile_conn_profile).
                where(:state => @states).
                where(:areacode => @cn).
                where(:type => @type).
                where(:anatel => @goal_filter).
                where(:pop => @pop)

            all_probes = Probe.
                where(:state => @states).
                where(:areacode => @cn).
                where(:type => @type).
                where(:anatel => @goal_filter).
                where(:pop => @pop).
                by_conn_type(@agent_type)
          end
        end
      end
    end


    fixed_schedules = Schedule.
        where(:destination_id => fixed_probes)

    mobile_schedules = Schedule.
        where(:destination_id => mobile_probes)

    all_schedules = Schedule.
        where(:destination_id => all_probes)


    @report_results = {}
    #
    #  SCM4
    #
    @report_results[:scm4] = {}
    @medians_scm4 = Median.
        where('start_timestamp >= ?', @from).
        where('end_timestamp <= ?', @to).
        where(:schedule_id => fixed_schedules).
        where(:threshold_id => 1).
        order('start_timestamp ASC').all
    #
    # SMP10
    #
    @report_results[:smp10] = {}
    @medians_smp10 = Median.
        where('start_timestamp >= ?', @from).
        where('end_timestamp <= ?', @to).
        where(:schedule_id => mobile_schedules).
        where(:threshold_id => 1).
        order('start_timestamp ASC').all
    #
    # SCM5
    #
    @report_results[:scm5] = {}
    @medians_scm5 = Median.
        where('start_timestamp >= ?', @from).
        where('end_timestamp <= ?', @to).
        where(:schedule_id => fixed_schedules).
        where(:threshold_id => 2).
        order('start_timestamp ASC').all

    #
    # SMP11
    #
    @report_results[:smp11] = {}
    @medians_smp11 = Median.
        where('start_timestamp >= ?', @from).
        where('end_timestamp <= ?', @to).
        where(:schedule_id => mobile_schedules).
        where(:threshold_id => 2).
        order('start_timestamp ASC').all

    #
    # SCM6
    #
    @report_results[:scm6] = {}
    @medians_scm6 = Median.
        where('start_timestamp >= ?', @from).
        where('end_timestamp <= ?', @to).
        where(:schedule_id => all_schedules).
        where(:threshold_id => 3).
        order('start_timestamp ASC').all

    #
    # SCM7
    #
    @report_results[:scm7] = {}
    @medians_scm7 = Median.
        where('start_timestamp >= ?', @from).
        where('end_timestamp <= ?', @to).
        where(:schedule_id => all_schedules).
        where(:threshold_id => 4).
        order('start_timestamp ASC').all

    #
    # SCM8
    #
    @report_results[:scm8] = {}
    @medians_scm8 = Median.
        where('start_timestamp >= ?', @from).
        where('end_timestamp <= ?', @to).
        where(:schedule_id => all_schedules).
        where(:threshold_id => 5).
        order('start_timestamp ASC').all

    #
    # SCM9
    #
    @report_results[:scm9] = {}
    @medians_scm9 = Median.
        where('start_timestamp >= ?', @from).
        where('end_timestamp <= ?', @to).
        where(:schedule_id => all_schedules).
        where(:threshold_id => 6).
        order('start_timestamp ASC').all

    #
    # Calculo de todas as medias de thresholds
    #
    @months.each do |month|
      # SCM4
      count4 = 0
      count_all4 = 0

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form3.html.erb
<%= form_tag(performance_reports_path, :class => 'form-horizontal', :id => 'report-form3') do %>
    <div class="row-fluid">
      <div class="span4">
        <div class="control-group">
          <label for="probe-state" class="control-label">UF:</label>

          <div class="controls">
            <select multiple="true" name="by_state[]" id="by_state">
              <option name="by_state" value="" selected="selected">Todas</option>
              <% Probe.states.each do |state| %>
                  <option value="<%= state.at(1) %>" <%= params[:by_state].to_s == state.at(1).to_s ? "selected=\"selected\"".html_safe : "" %>><%= state.at(1).upcase %></option>
              <% end %>
            </select>
          </div>
        </div>
        <div class="control-group">
          <label class="control-label" for="pop">POP: </label>

          <div class="controls">
            <select multiple="true" name="by_pop[]" id="by_pop">
              <option value="" selected>Todas</option>
              <% Probe.pops.each do |p| %>
                  <option value="<%= p %>"><%= p %></option>
              <% end %>
            </select>
          </div>
        </div>
      </div>
      <div class="span6 offset1">
        <div class="control-group">
          <label class="control-label" for="by_type">Tipo de Destino: </label>

          <div class="controls">
            <%= select :by_type, '', Probe.types, :onchange => 'displayTypes(this.value)', :id => "by_type", :include_blank => "Todos" %>
          </div>
        </div>
        <div id="ag_types" class="control-group">
          <label class="control-label" for="by_conn_type">Tipo de Conexão: </label>

          <div class="controls">
            <%= select :by_conn_type, '', [['Todos', ''], ['Móvel', 'mobile'], ["Fixo", "fixed"]] %>
          </div>
        </div>
        <div class="control-group">
          <label class="control-label" for="modem">Modem: </label>

          <div class="controls">
            <select name="by_modem[]" id="by_modem">
              <option value="">Todos</option>
              <% Probe.modems.each do |p| %>
                  <option value="<%= p %>"><%= p %></option>
              <% end %>
            </select>
          </div>
        </div>
        <div class="control-group">
          <label class="control-label" for="by_tech">Tecnologia: </label>

          <div class="controls">
            <select name="by_tech[]" id="by_tech">
              <option value="">Todas</option>
              <% Probe.techs.each do |p| %>
                  <option value="<%= p %>"><%= p %></option>
              <% end %>
            </select>
          </div>
        </div>
      </div>
    </div>

    <div class="row-fluid" style="border-top: 1px solid #CCCCCC;">
      <div class="span7">
        <div class="control-group" style="margin-top: 10px">
          <label class="control-label" for="destino">Sonda de Destino: </label>

          <div class="controls ">
            <select class="input-block-level" name="destination[id]" id="destino">
              <option value=""> Selecione um UF primeiro...</option>
              <!--%= collection_select :destination, :id, Probe.order(:name).all, :id, :pretty_name_with_location, {:include_blank => "Selecione..."}, {:class => 'input-block-level',:id=>"destino"} %>
            -->
            </select>

            <div id="alert_dest" class="alert alert-error" style="display: none">
              Você deve selecionar pelo menos um UF válido.
            </div>
          </div>
        </div>

        <div class="control-group">
          <label for="source_id" class="control-label">Sonda de Origem:</label>

          <div class="controls">
            <%= collection_select :source, :id, {}, :id, :pretty_name_with_location, {:include_blank => "Selecione a sonda de destino primeiro"}, {:class => 'input-block-level', :id => "origem"} %>
          </div>
        </div>
      </div>
    </div>

    <div class="row-fluid" style="border-top: 1px solid #CCCCCC;">
      <div style="margin-top: 10px">
        <div class="span6">
          <div class="control-group">
            <span class="control-label">Métricas:</span>

            <div class="controls">
              <select id="metrics" name="metrics[]">
                <% Metric.order('"order" ASC').all.each do |m| %>
                    <option value="<%= m.id %>,<%= m.metric_type %>"><%= m.name %></option>
                <% end %>
              </select>
            </div>
          </div>
          <div class="control-group">
            <label class="control-label" for="horario">Horário: </label>

            <div class="controls">
              <%= select :horario, '', [['Últimas 24h', '24'], ["Últimas 48h", '48'], ['Últimas 72h', '72']] %>
            </div>
          </div>
        </div>
        <div class="span6">
          <div id="sites" class="control-group" style="display: none">
            <span class="control-label">Sites:</span>

            <div class="controls">
              <select multiple="true" name="by_sites[]">
                <option value="" selected>Todos</option>
                <% Site.all.each do |site| %>
                    <option value="<%= site.url %>"><%= site.url %></option>
                <% end %>
              </select>
            </div>
          </div>
          <div id="dns" class="control-group" style="display: none">
            <span class="control-label">Servidor DNS:</span>

            <div class="controls">
              <select multiple="true" name="by_dns[]">
                <option value="" selected>Todos</option>
                <% Nameserver.all.each do |dns| %>
                    <option value="<%= dns.address %>"><%= dns.name %> (<%= dns.address %>)</option>
                <% end %>
              </select>
            </div>
          </div>
          <div id="variation" class="control-group" style="display:block">
            <span class="control-label">Variação Métrica:</span>

            <div class="controls">
              <%= select :variation, '', [["Média", "avg"], ["Mínimo", "min"], ["Máximo", "max"]] %>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="row-fluid ">
      <div class="span6">
        <div class="control-group">
          <div class="controls">
            <input class="btn btn-primary" type="submit" name="add" id="report-add3" value="Adicionar" data-toggle="collapse" data-target="#accordion_forms"/>
          </div>
        </div>
      </div>
    </div>
<% end %>

<script>
    jQuery('#metrics').change(function () {
        var value = $(this).val();
        var type = value.split(',')[1];

        if (type == "webload") {
            $('#sites').attr('style', 'display:block');
            $('#dns').attr('style', 'display:none');
            $('#variation').attr('style', 'display:none');
        } else if (type == "dns" || type == "dns_detail") {
            $('#sites').attr('style', 'display:block');
            $('#dns').attr('style', 'display:block');
            $('#variation').attr('style', 'display:none');
        } else if (type == "active") {
            $('#sites').attr('style', 'display:none');
            $('#dns').attr('style', 'display:none');
            $('#variation').attr('style', 'display:block');
        } else {
            $('#sites').attr('style', 'display:none');
            $('#dns').attr('style', 'display:none');
            $('#variation').attr('style', 'display:none');
        }


    });


    jQuery('#by_state').change(function () {
                filter_all();
            }
    );
    jQuery('#by_pop').change(function () {
                filter_all();
            }
    );
    jQuery('#by_type_').change(function () {
                filter_all();
            }
    );
    jQuery('#by_modem').change(function () {
                filter_all();
            }
    );
    jQuery('#by_tech').change(function () {
                filter_all();
            }
    );
    jQuery('#by_conn_type_').change(function () {
                filter_all();
            }
    );

    $('#report-add3').click(function () {
        $("#optbtn").attr('src', '<%= image_path 'opt_btn-right.png' %>');
        $("#optbtn").attr('name', 'closed');

    });

    function setAllOpt(value, id) {

        if (value == "" || value == 1 || value == "all") {
            var aux = document.getElementById(id).options;
            aux.selected = false;
            for (var i = 0; i < aux.length; i++) {
                aux.item(i).selected = true;
            }
        }

        return  $('select#' + id).val();
    }

    function filter_all() {
        var ufs;
        ufs = jQuery('#by_state').val();
        //ufs = setAllOpt(ufs, 'by_state');
        var pops = jQuery('#by_pop').val();
        var type = jQuery('#by_type_').val();
        var modem = jQuery('#by_modem').val();
        var techs = jQuery('#by_tech').val();
        var conn_type = jQuery('#by_conn_type_').val();


        $.ajax({
            type: 'GET',
            dataType: 'json',
            url: "<%= probes_url %>",
            data: {
                'by_state': ufs,
                'by_pop': pops,
                'by_type': type,
                'by_modem': modem,
                'by_tech': techs,
                'by_conn_type': conn_type

            },
            success: function (data) {
                var html = "";
                if (data == "") {
                    html = "<option value='not'>Não há sonda para estes filtros selecionados.</option>";
                    $('#origem').html("<option value=''>Selecione a sonda de destino primeiro</option>");
                } else {
                    $('#alert_dest').attr('style', 'display:none');
                    $('#origem').html("<option value=''>Todas</option>");
                    html = html + "<option value=''>Todas</option>";
                    for (p in data) {
                        html = html + "<option value='" + data[p]["id"] + "'>" + data[p]["name"] + " (" + data[p]["ipaddress"] + ")</option>";
                    }
                }
                $('#destino').html(html);

            },
            headers: {
                'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
            }
        });

    }

    jQuery("#destino").change(function (evt) {
        var destination_id = evt.currentTarget.value;
        if (destination_id != '')
            jQuery.ajax("<%=probes_url %>/" + destination_id + "/sources", {
                success: function (result, status) {
                    var options = jQuery('#origem');
                    options.html('');
                    options.removeAttr('disabled');
                    jQuery.each(result, function (index, item) {
                        options.append($("<option />").val(item.id).text(item.name + ' (' + item.ipaddress + ') - ' + item.city + '/' + item.state.toUpperCase()));
                        jQuery("#origem").trigger('change');
                    });
                    if (result.length == 0) {
                        options.append($("<option />").val('').text('Essa sonda não recebe testes')).prop('disabled', true);
                    }
                },
                dataType: 'json',
                headers: {
                    'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
                }
            });
        else {
            jQuery('#origem').html('').append($("<option />").val('').text('Selecione a sonda de destino primeiro')).prop('disabled', true).trigger('change');

        }

    });

    jQuery('#report-form3').submit(function (event) {
        event.preventDefault();
        var dest = $('#destino').val();

        if (dest == "not") {
            $('#alert_dest').attr('style', 'display:block');
            $('#accordion_forms').attr("class", "collapse width in");
            $('#accordion_forms').attr("style", "width: auto");
        } else {
            $("html, body").animate({ scrollTop: 0 }, "slow");
            $('#accordion_forms').attr("class", "collapse width");
            $('#accordion_forms').attr("style", "width: 0px");

            jQuery.ajax("<%= performance_reports_url %>", {
                data: $(this).serialize(),
                type: 'POST',
                beforeSend: function () {
                        jQuery('#graphs-area').prepend('<div id=\"row-loading\" class="row-fluid"><div   class=\"span12\"><div id=\"box-loading\" style="height:100px;"><%=image_tag 'ajax-loader.gif' %> <strong>Requisitando o relatório selecionado, aguarde...</strong></div></div></div>');
                    },
                complete: function (obj, status) {
                    jQuery('#row-loading').remove();
                },
                error: function (obj, status) {
                    console.log(obj);
                    console.log("Query Error " + status);
                },
                success: function (result) {
                    jQuery('#graphs-area').prepend(result);
                },
                headers: {
                    'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
                }
            });
        }

    });

</script>

app/views/reports/performance.html.erb
<div id="many-graphs" class="row-fluid">
  <% @probes.each do |probe|  %>
      <%= probe.name %>
  <% end %>
  <% @schedules.each do |sch|  %>
      <%= sch.id %>
  <% end %>
</div>